// Auto-generated by scripts/generate-html-template.js - DO NOT EDIT MANUALLY
export const PRODUCTION_HTML_TEMPLATE = `<!doctype html>
<html lang="vi">
  <head>
    <meta charset="UTF-8" />

    <script>
      // Safe environment shim: Ensure window.fetch is writable and cannot throw getter-only TypeError
      (function() {
        try {
          var originalFetch = typeof window !== 'undefined' && window.fetch ? window.fetch.bind(window) : undefined;
          if (typeof window !== 'undefined') {
            var proto = window;
            while (proto) {
              var desc = Object.getOwnPropertyDescriptor(proto, 'fetch');
              if (desc) {
                if (!desc.set && desc.configurable !== false) {
                  var activeFetch = originalFetch;
                  Object.defineProperty(window, 'fetch', {
                    get: function() { return activeFetch; },
                    set: function(val) { activeFetch = val; },
                    configurable: true,
                    enumerable: true
                  });
                }
                break;
              }
              proto = Object.getPrototypeOf(proto);
            }
          }
        } catch (e) {}
      })();
    </script>

    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0"
    />

    <title>DK TEST - Hệ thống thi trực tuyến</title>

    <meta
      name="description"
      content="DK TEST - Hệ thống tạo, quản lý và tham gia các bài kiểm tra trực tuyến."
    />

    <meta name="theme-color" content="#0f172a" />

    <!-- Open Graph -->
    <meta property="og:type" content="website" />
    <meta property="og:title" content="DK TEST - Hệ thống thi trực tuyến" />
    <meta
      property="og:description"
      content="Tạo đề, tổ chức kỳ thi và làm bài trực tuyến với DK TEST."
    />
    <meta property="og:site_name" content="DK TEST" />
    <meta property="og:image" content="/logo.png" />

    <!-- Twitter / X -->
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="DK TEST - Hệ thống thi trực tuyến" />
    <meta
      name="twitter:description"
      content="Tạo đề, tổ chức kỳ thi và làm bài trực tuyến với DK TEST."
    />
    <meta name="twitter:image" content="/logo.png" />

    <!-- Favicon -->
    <link rel="icon" type="image/png" href="/favicon.png" />
    <link rel="icon" type="image/x-icon" href="/favicon.ico" />
    <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
    <script type="module" crossorigin src="/assets/index-BKBuBTzK.js"></script>
    <link rel="stylesheet" crossorigin href="/assets/index-C6988nVu.css">
  </head>

  <body>
    <div id="root"></div>

  </body>
</html>`;
