// Auto-generated by scripts/generate-html-template.js - DO NOT EDIT MANUALLY
export const PRODUCTION_HTML_TEMPLATE = `<!doctype html>
<html lang="vi">
  <head>
    <meta charset="UTF-8" />

    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0"
    />

    <title>DK TEST - Hệ thống thi trực tuyến</title>

    <meta
      name="description"
      content="DK TEST - Hệ thống tạo, quản lý và tham gia các bài kiểm tra trực tuyến."
    />

    <meta name="theme-color" content="#0f172a" />

    <!-- Open Graph -->
    <meta property="og:type" content="website" />
    <meta property="og:title" content="DK TEST - Hệ thống thi trực tuyến" />
    <meta
      property="og:description"
      content="Tạo đề, tổ chức kỳ thi và làm bài trực tuyến với DK TEST."
    />
    <meta property="og:site_name" content="DK TEST" />

    <!-- Twitter / X -->
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="DK TEST - Hệ thống thi trực tuyến" />
    <meta
      name="twitter:description"
      content="Tạo đề, tổ chức kỳ thi và làm bài trực tuyến với DK TEST."
    />

    <!-- Favicon -->
    <link rel="icon" type="image/png" href="/favicon.png" />

    <!-- Prevent favicon 404 if you don't have one yet -->
    <link rel="apple-touch-icon" href="/favicon.png" />
    <script type="module" crossorigin src="/assets/index-cHzg-EnA.js"></script>
    <link rel="stylesheet" crossorigin href="/assets/index-Nmyn60pj.css">
  </head>

  <body>
    <div id="root"></div>

  </body>
</html>`;
