// Auto-generated by scripts/generate-html-template.js - DO NOT EDIT MANUALLY
export const PRODUCTION_HTML_TEMPLATE = `<!doctype html>
<html lang="vi">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0, viewport-fit=cover" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <title>DK TEST - Hệ thống thi trực tuyến</title>

    <meta
      name="description"
      content="DK TEST - Hệ thống tạo, quản lý và tham gia các bài kiểm tra trực tuyến."
    />
    <meta name="theme-color" content="#0f172a" />

    <!-- Open Graph -->
    <meta property="og:type" content="website" />
    <meta property="og:title" content="DK TEST - Hệ thống thi trực tuyến" />
    <meta
      property="og:description"
      content="Tạo đề, tổ chức kỳ thi và làm bài trực tuyến với DK TEST."
    />
    <meta property="og:site_name" content="DK TEST" />
    <meta property="og:image" content="/logo.png" />

    <!-- Twitter / X -->
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="DK TEST - Hệ thống thi trực tuyến" />
    <meta
      name="twitter:description"
      content="Tạo đề, tổ chức kỳ thi và làm bài trực tuyến với DK TEST."
    />
    <meta name="twitter:image" content="/logo.png" />

    <!-- Favicon -->
    <link rel="icon" type="image/png" href="/favicon.png" />
    <link rel="icon" type="image/x-icon" href="/favicon.ico" />
    <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
    <link rel="manifest" href="/manifest.json" />

    <!-- Pre-Boot Resilience & Anti-Blank Screen Shield -->
    <script>
      (function() {
        // Theme Pre-boot initialization (avoids FOUC)
        try {
          var savedTheme = localStorage.getItem('dktest_theme');
          var systemDark = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches;
          if (savedTheme === 'dark' || ((!savedTheme || savedTheme === 'system') && systemDark)) {
            document.documentElement.classList.add('dark');
          } else {
            document.documentElement.classList.remove('dark');
          }
        } catch (e) {}

        // 0. Ancient Browser Detection Guard (Pre-ES6 check)
        if (typeof Promise === 'undefined' || typeof Symbol === 'undefined' || typeof Map === 'undefined') {
          window.__DK_BROWSER_UNSUPPORTED__ = true;
          window.addEventListener('DOMContentLoaded', function() {
            var root = document.getElementById('root');
            if (root) {
              root.innerHTML = '<div style="min-height:100vh;background:#0f172a;color:#fff;display:flex;align-items:center;justify-content:center;padding:24px;text-align:center;font-family:system-ui,sans-serif;"><div style="max-width:400px;background:#1e293b;border-radius:24px;padding:32px;border:1px solid #334155;"><h2 style="font-size:20px;font-weight:800;color:#f87171;margin-bottom:12px;">Trình duyệt quá cũ</h2><p style="font-size:13px;color:#94a3b8;line-height:1.6;margin-bottom:20px;">Phiên bản trình duyệt của bạn không còn đáp ứng tiêu chuẩn bảo mật cho kỳ thi trực tuyến. Vui lòng mở DkTEST bằng Google Chrome bản mới trên CH Play hoặc Cốc Cốc.</p><a href="https://www.google.com/chrome/" target="_blank" style="display:inline-block;padding:12px 24px;background:#2563eb;color:#fff;border-radius:12px;text-decoration:none;font-size:13px;font-weight:700;">Tải Google Chrome</a></div></div>';
            }
          });
          return;
        }

        // 1. Safe fetch property shim
        try {
          var originalFetch = typeof window !== 'undefined' && window.fetch ? window.fetch.bind(window) : undefined;
          if (typeof window !== 'undefined') {
            var proto = window;
            while (proto) {
              var desc = Object.getOwnPropertyDescriptor(proto, 'fetch');
              if (desc) {
                if (!desc.set && desc.configurable !== false) {
                  var activeFetch = originalFetch;
                  Object.defineProperty(window, 'fetch', {
                    get: function() { return activeFetch; },
                    set: function(val) { activeFetch = val; },
                    configurable: true,
                    enumerable: true
                  });
                }
                break;
              }
              proto = Object.getPrototypeOf(proto);
            }
          }
        } catch (e) {}

        // 2. Safe Storage Shim (handles Private Browsing / SecurityError on Chrome Android)
        try {
          var storageTest = window.localStorage;
          storageTest.setItem('__dk_test__', '1');
          storageTest.removeItem('__dk_test__');
        } catch (storageErr) {
          try {
            var mem = {};
            var createStoragePolyfill = function() {
              return {
                getItem: function(k) { return mem[k] !== undefined ? mem[k] : null; },
                setItem: function(k, v) { mem[k] = String(v); },
                removeItem: function(k) { delete mem[k]; },
                clear: function() { mem = {}; },
                get length() { return Object.keys(mem).length; },
                key: function(i) { return Object.keys(mem)[i] || null; }
              };
            };
            Object.defineProperty(window, 'localStorage', { value: createStoragePolyfill(), configurable: true });
            Object.defineProperty(window, 'sessionStorage', { value: createStoragePolyfill(), configurable: true });
          } catch (polyErr) {}
        }

        // 3. structuredClone shim
        if (typeof window !== 'undefined' && typeof window.structuredClone === 'undefined') {
          window.structuredClone = function(obj) {
            try {
              return JSON.parse(JSON.stringify(obj));
            } catch (err) {
              return obj;
            }
          };
        }

        // 4. crypto.randomUUID shim (Safe for HTTP / older Android WebViews)
        if (typeof window !== 'undefined' && window.crypto && !window.crypto.randomUUID) {
          window.crypto.randomUUID = function() {
            return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) { 
              var r = Math.random() * 16 | 0;
              var v = c === 'x' ? r : (r & 0x3 | 0x8);
              return v.toString(16);
            });
          };
        }

        // 5. AbortSignal.timeout shim (Added in Chrome 103, absent in Chrome 101)
        if (typeof AbortSignal !== 'undefined' && !AbortSignal.timeout) {
          AbortSignal.timeout = function(ms) {
            var controller = new AbortController();
            setTimeout(function() {
              try {
                controller.abort(new DOMException('The operation timed out.', 'TimeoutError'));
              } catch (e) {
                controller.abort();
              }
            }, ms);
            return controller.signal;
          };
        }

        // 6. URL.canParse shim (Added in Chrome 120, absent in Chrome 101)
        if (typeof URL !== 'undefined' && !URL.canParse) {
          URL.canParse = function(url, base) {
            try {
              new URL(url, base);
              return true;
            } catch (e) {
              return false;
            }
          };
        }

        // 7. Object.hasOwn shim (Chrome 93+)
        if (typeof Object !== 'undefined' && !Object.hasOwn) {
          Object.hasOwn = function(obj, prop) {
            return Object.prototype.hasOwnProperty.call(obj, prop);
          };
        }

        // 8. Array.prototype.at & String.prototype.at shim (Chrome 92+)
        if (typeof Array !== 'undefined' && !Array.prototype.at) {
          Array.prototype.at = function(n) {
            n = Math.trunc(n) || 0;
            if (n < 0) n += this.length;
            if (n < 0 || n >= this.length) return undefined;
            return this[n];
          };
        }
        if (typeof String !== 'undefined' && !String.prototype.at) {
          String.prototype.at = function(n) {
            n = Math.trunc(n) || 0;
            if (n < 0) n += this.length;
            if (n < 0 || n >= this.length) return "";
            return this.charAt(n);
          };
        }

        // 9. ResizeObserver & IntersectionObserver safety shims for restricted WebViews
        if (typeof window !== 'undefined' && !window.ResizeObserver) {
          window.ResizeObserver = function() {
            this.observe = function() {};
            this.unobserve = function() {};
            this.disconnect = function() {};
          };
        }
        if (typeof window !== 'undefined' && !window.IntersectionObserver) {
          window.IntersectionObserver = function() {
            this.observe = function() {};
            this.unobserve = function() {};
            this.disconnect = function() {};
          };
        }

        // 10. navigator.clipboard shim
        if (typeof navigator !== 'undefined' && !navigator.clipboard) {
          navigator.clipboard = {
            writeText: function(text) {
              return new Promise(function(resolve, reject) {
                try {
                  var textarea = document.createElement('textarea');
                  textarea.value = String(text || '');
                  textarea.style.position = 'fixed';
                  textarea.style.opacity = '0';
                  textarea.style.pointerEvents = 'none';
                  document.body.appendChild(textarea);
                  textarea.focus();
                  textarea.select();
                  var success = document.execCommand('copy');
                  document.body.removeChild(textarea);
                  if (success) resolve(); else reject(new Error('execCommand copy failed'));
                } catch (e) {
                  reject(e);
                }
              });
            },
            readText: function() {
              return Promise.resolve('');
            }
          };
        }

        // 11. BroadcastChannel shim (for older WebViews)
        if (typeof window !== 'undefined' && typeof window.BroadcastChannel === 'undefined') {
          window.BroadcastChannel = function(name) {
            this.name = name;
            this.onmessage = null;
            this.onmessageerror = null;
            this.postMessage = function(data) {
              try {
                if (typeof window.localStorage !== 'undefined') {
                  window.localStorage.setItem('__dk_bc_' + name, JSON.stringify({ d: data, t: Date.now() }));
                }
              } catch(e) {}
            };
            this.close = function() {};
          };
        }

        // 12. Fullscreen API safe fallback shims
        if (typeof Element !== 'undefined' && !Element.prototype.requestFullscreen) {
          Element.prototype.requestFullscreen =
            Element.prototype.webkitRequestFullscreen ||
            Element.prototype.mozRequestFullScreen ||
            Element.prototype.msRequestFullscreen ||
            function() { return Promise.resolve(); };
        }
        if (typeof Document !== 'undefined' && !Document.prototype.exitFullscreen) {
          Document.prototype.exitFullscreen =
            Document.prototype.webkitExitFullscreen ||
            Document.prototype.mozCancelFullScreen ||
            Document.prototype.msExitFullscreen ||
            function() { return Promise.resolve(); };
        }

        // 13. requestIdleCallback shim
        if (typeof window !== 'undefined' && !window.requestIdleCallback) {
          window.requestIdleCallback = function(cb) {
            return setTimeout(function() {
              cb({ didTimeout: false, timeRemaining: function() { return 50; } });
            }, 1);
          };
          window.cancelIdleCallback = function(id) { clearTimeout(id); };
        }

        // 14. Early Zombie ServiceWorker Cleanup
        if (typeof navigator !== 'undefined' && 'serviceWorker' in navigator) {
          try {
            navigator.serviceWorker.getRegistrations().then(function(regs) {
              for (var i = 0; i < regs.length; i++) {
                regs[i].unregister().catch(function() {});
              }
            }).catch(function() {});
          } catch (e) {}
        }

        // 9. Early ChunkLoadError auto-recovery listener
        var CHUNK_KEY = 'dk_last_chunk_recovery';
        var handleEarlyChunkError = function(msg) {
          var text = String(msg || '').toLowerCase();
          if (
            text.indexOf('chunk') !== -1 ||
            text.indexOf('dynamically imported module') !== -1 ||
            text.indexOf('loading css chunk') !== -1 ||
            text.indexOf('failed to fetch') !== -1
          ) {
            var last = sessionStorage.getItem(CHUNK_KEY);
            var now = Date.now();
            if (!last || (now - parseInt(last, 10)) > 30000) {
              sessionStorage.setItem(CHUNK_KEY, String(now));
              var clean = new URL(window.location.href);
              clean.searchParams.set('_r', String(now));
              window.location.replace(clean.toString());
            }
          }
        };

        window.addEventListener('error', function(e) {
          handleEarlyChunkError(e.message || (e.error && e.error.message));
        });
        window.addEventListener('unhandledrejection', function(e) {
          handleEarlyChunkError(e.reason && (e.reason.message || e.reason));
        });
      })();
    </script>

    <style>
      /* Zero-FOUC Initial App Shell */
      html, body {
        margin: 0;
        padding: 0;
        background-color: #0f172a;
        color: #f8fafc;
        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
        -webkit-tap-highlight-color: transparent;
        text-size-adjust: 100%;
        -webkit-text-size-adjust: 100%;
        overflow-x: hidden;
        max-width: 100vw;
      }
      .dk-boot-shell {
        min-height: 100vh;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        padding: 20px;
        text-align: center;
        background: #0f172a;
        box-sizing: border-box;
      }
      @supports (min-height: 100dvh) {
        .dk-boot-shell {
          min-height: 100dvh;
        }
      }
      .dk-boot-logo {
        width: 60px;
        height: 60px;
        border-radius: 18px;
        background: linear-gradient(135deg, #2563eb 0%, #1d4ed8 100%);
        box-shadow: 0 10px 25px -5px rgba(37, 99, 235, 0.4);
        display: flex;
        align-items: center;
        justify-content: center;
        margin-bottom: 20px;
        animation: dk-pulse 2s infinite ease-in-out;
      }
      .dk-boot-title {
        font-size: 20px;
        font-weight: 800;
        letter-spacing: -0.02em;
        color: #ffffff;
        margin-bottom: 6px;
      }
      .dk-boot-sub {
        font-size: 13px;
        color: #94a3b8;
        font-weight: 500;
        margin-bottom: 20px;
      }
      .dk-boot-bar {
        width: 140px;
        height: 4px;
        border-radius: 2px;
        background: #1e293b;
        overflow: hidden;
        position: relative;
      }
      .dk-boot-bar::after {
        content: '';
        position: absolute;
        top: 0;
        left: 0;
        height: 100%;
        width: 40%;
        background: #3b82f6;
        border-radius: 2px;
        animation: dk-slide 1.4s infinite ease-in-out;
      }
      @keyframes dk-pulse {
        0%, 100% { transform: scale(1); }
        50% { transform: scale(1.05); }
      }
      @keyframes dk-slide {
        0% { left: -40%; }
        50% { left: 40%; }
        100% { left: 100%; }
      }
    </style>
    <script type="module" crossorigin src="/assets/index-D5mVTjEz.js"></script>
    <link rel="modulepreload" crossorigin href="/assets/vendor-react-Cg2vLLvP.js">
    <link rel="modulepreload" crossorigin href="/assets/vendor-charts-DkJUajiB.js">
    <link rel="modulepreload" crossorigin href="/assets/vendor-icons-gUCkgdYI.js">
    <link rel="modulepreload" crossorigin href="/assets/vendor-firebase-BvmnIVAj.js">
    <link rel="modulepreload" crossorigin href="/assets/vendor-katex-T051Jbj4.js">
    <link rel="modulepreload" crossorigin href="/assets/vendor-mathlive-ChYs3Gtv.js">
    <link rel="stylesheet" crossorigin href="/assets/vendor-katex-Ddr6Z9Sf.css">
    <link rel="stylesheet" crossorigin href="/assets/index-CPaHX8eD.css">
  </head>

  <body>
    <!-- App Root with sleek Instant Boot Shell (Replaced instantly when React mounts) -->
    <div id="root">
      <div class="dk-boot-shell">
        <div class="dk-boot-logo">
          <svg style="width:32px;height:32px;color:#ffffff;" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2.2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
          </svg>
        </div>
        <div class="dk-boot-title">DkTEST</div>
        <div class="dk-boot-sub">Đang khởi động hệ thống thi...</div>
        <div class="dk-boot-bar"></div>
      </div>
    </div>

  </body>
</html>`;
