const CULTIVATION_REALMS = [
  { name: "Luyện Khí", emoji: "🌬️", tiers: 10 },
  { name: "Trúc Cơ", emoji: "🌿", tiers: 10 },
  { name: "Kim Đan", emoji: "💎", tiers: 10 },
  { name: "Nguyên Anh", emoji: "✨", tiers: 10 },
  { name: "Hóa Thần", emoji: "☄️", tiers: 10 },
  { name: "Luyện Hư", emoji: "🌠", tiers: 10 },
  { name: "Hợp Thể", emoji: "🌀", tiers: 10 },
  { name: "Độ Kiếp", emoji: "⚡", tiers: 10 },
  { name: "Đại Thừa", emoji: "🌌", tiers: 10 },

  // Tiên giới
  { name: "Bán Tiên", emoji: "🌙", tiers: 10 },
  { name: "Nhân Tiên", emoji: "👤", tiers: 10 },
  { name: "Địa Tiên", emoji: "🌍", tiers: 10 },
  { name: "Thiên Tiên", emoji: "☁️", tiers: 10 },
  { name: "Huyền Tiên", emoji: "🔷", tiers: 10 },
  { name: "Kim Tiên", emoji: "🥇", tiers: 10 },
  { name: "Thái Ất Kim Tiên", emoji: "⭐", tiers: 10 },
  { name: "Đại La Kim Tiên", emoji: "🌟", tiers: 10 },
  { name: "Tiên Vương", emoji: "👑", tiers: 10 },
  { name: "Tiên Hoàng", emoji: "🏯", tiers: 10 },
  { name: "Tiên Đế", emoji: "🪷", tiers: 10 },

  // Thần giới
  { name: "Chân Thần", emoji: "🔥", tiers: 10 },
  { name: "Thiên Thần", emoji: "🌞", tiers: 10 },
  { name: "Thần Vương", emoji: "⚜️", tiers: 10 },
  { name: "Thần Hoàng", emoji: "💠", tiers: 10 },
  { name: "Thần Đế", emoji: "💫", tiers: 10 },
  { name: "Thần Tôn", emoji: "🛕", tiers: 10 },

  // Chí cao
  { name: "Đạo Tổ", emoji: "☯️", tiers: 10 },
  { name: "Đạo Tôn", emoji: "🕉️", tiers: 10 },
  { name: "Đạo Chủ", emoji: "🌐", tiers: 10 },
  { name: "Đạo Quân", emoji: "⚜️", tiers: 10 },
  { name: "Thiên Đạo", emoji: "♾️", tiers: 10 },
];
// --- HỆ THỐNG VẬT PHẨM MỞ RỘNG ---
const GAME_SHOP_ITEMS = {
  // ĐAN DƯỢC (type: dan)
  "tieu-hoan-dan": {
    type: "dan",
    name: "Tiểu Hoàn Đan",
    emoji: "💊",
    price: 50,
    effect: "+10 Linh khí",
    desc: "Giúp khôi phục chút ít linh lực.",
    stats: { linhKhi: 10 },
  },
  "dai-hoan-dan": {
    type: "dan",
    name: "Đại Hoàn Đan",
    emoji: "🔴",
    price: 150,
    effect: "+40 Linh khí",
    desc: "Phiên bản nâng cấp, linh khí nồng đậm.",
    stats: { linhKhi: 40 },
  },
  "boi-nguyen-dan": {
    type: "dan",
    name: "Bồi Nguyên Đan",
    emoji: "🟢",
    price: 250,
    effect: "+70 Linh khí",
    desc: "Củng cố căn cơ, bồi dưỡng nguyên khí.",
    stats: { linhKhi: 70 },
  },
  "truc-co-dan": {
    type: "dan",
    name: "Trúc Cơ Đan",
    emoji: "💠",
    price: 1000,
    effect: "+5 May mắn",
    desc: "Đan dược tăng tỷ lệ độ kiếp thành công.",
    stats: { luck: 5 },
  },
  "pha-chuong-dan": {
    type: "dan",
    name: "Phá Chướng Đan",
    emoji: "⚡",
    price: 2500,
    effect: "+5 May mắn, +5 Thân pháp",
    desc: "Giúp bài trừ tâm ma, độ kiếp dễ dàng.",
    stats: { luck: 5, agility: 5 },
  },
  // ===== ĐAN DƯỢC =====
  "tu-linh-dan": {
    type: "dan",
    name: "Tụ Linh Đan",
    emoji: "🧿",
    price: 400,
    effect: "+100 Linh khí",
    stats: { linhKhi: 100 },
  },
  "thien-linh-dan": {
    type: "dan",
    name: "Thiên Linh Đan",
    emoji: "🌌",
    price: 800,
    effect: "+180 Linh khí",
    stats: { linhKhi: 180 },
  },
  "cuong-the-dan": {
    type: "dan",
    name: "Cường Thể Đan",
    emoji: "💪",
    price: 1200,
    effect: "+15 HP",
    stats: { hp_bonus: 15 },
  },
  "kim-cuong-dan": {
    type: "dan",
    name: "Kim Cương Đan",
    emoji: "🪨",
    price: 2000,
    effect: "+15 Phòng thủ",
    stats: { defense: 15 },
  },
  "than-hanh-dan": {
    type: "dan",
    name: "Thần Hành Đan",
    emoji: "💨",
    price: 1600,
    effect: "+12 Thân pháp",
    stats: { agility: 12 },
  },
  "chien-than-dan": {
    type: "dan",
    name: "Chiến Thần Đan",
    emoji: "⚔️",
    price: 2800,
    effect: "+20 Sức mạnh",
    stats: { power: 20 },
  },
  "thien-van-dan": {
    type: "dan",
    name: "Thiên Vận Đan",
    emoji: "🍀",
    price: 3200,
    effect: "+12 May mắn",
    stats: { luck: 12 },
  },
  "vo-cuc-dan": {
    type: "dan",
    name: "Vô Cực Đan",
    emoji: "☯️",
    price: 6000,
    effect: "+40 Linh khí, +15 Sức",
    stats: { linhKhi: 40, power: 15 },
  },
  "bat-hoang-dan": {
    type: "dan",
    name: "Bát Hoang Đan",
    emoji: "🌋",
    price: 8000,
    effect: "+30 Sức, +10 Thủ",
    stats: { power: 30, defense: 10 },
  },
  "truong-sinh-dan": {
    type: "dan",
    name: "Trường Sinh Đan",
    emoji: "🌿",
    price: 12000,
    effect: "+80 HP",
    stats: { hp_bonus: 80 },
  },

  "ngo-dao-dan": {
    type: "dan",
    name: "Ngộ Đạo Đan",
    emoji: "🪷",
    price: 50000,
    effect: "+5% Ngộ đạo",
    stats: { xpRate: 5 },
  },
  "dai-ngo-dao-dan": {
    type: "dan",
    name: "Đại Ngộ Đạo Đan",
    emoji: "✨",
    price: 120000,
    effect: "+12% Ngộ đạo",
    stats: { xpRate: 12 },
  },
  "thien-dao-dan": {
    type: "dan",
    name: "Thiên Đạo Đan",
    emoji: "🌠",
    price: 250000,
    effect: "+25% Ngộ đạo",
    stats: { xpRate: 25 },
  },

  "kinh-nghiem-dan": {
    type: "dan",
    name: "Kinh Nghiệm Đan",
    emoji: "📘",
    price: 1000,
    effect: "+500 XP",
    stats: { xp: 500 },
  },
  "cao-cap-kinh-nghiem-dan": {
    type: "dan",
    name: "Cao Cấp Kinh Nghiệm Đan",
    emoji: "📙",
    price: 5000,
    effect: "+3000 XP",
    stats: { xp: 3000 },
  },
  "vo-thuong-kinh-nghiem-dan": {
    type: "dan",
    name: "Vô Thượng Kinh Nghiệm Đan",
    emoji: "📕",
    price: 20000,
    effect: "+15000 XP",
    stats: { xp: 15000 },
  },

  "hon-nguyen-dan": {
    type: "dan",
    name: "Hỗn Nguyên Đan",
    emoji: "🔮",
    price: 7000,
    effect: "+25 Linh khí, +10 May",
    stats: { linhKhi: 25, luck: 10 },
  },
  "thanh-long-dan": {
    type: "dan",
    name: "Thanh Long Đan",
    emoji: "🐉",
    price: 14000,
    effect: "+45 Sức mạnh",
    stats: { power: 45 },
  },
  "bach-ho-dan": {
    type: "dan",
    name: "Bạch Hổ Đan",
    emoji: "🐯",
    price: 14000,
    effect: "+35 Phòng thủ",
    stats: { defense: 35 },
  },
  "chu-tuoc-dan": {
    type: "dan",
    name: "Chu Tước Đan",
    emoji: "🔥",
    price: 15000,
    effect: "+80 Linh khí",
    stats: { linhKhi: 80 },
  },
  "hoi-huyet-dan": {
    type: "dan",
    name: "Hồi Huyết Đan",
    emoji: "🩸",
    price: 200,
    effect: "Hồi 50 HP",
    desc: "Đan dược chữa thương cơ bản.",
    heal: 50,
  },

  "trung-cap-hoi-huyet-dan": {
    type: "dan",
    name: "Trung Phẩm Hồi Huyết Đan",
    emoji: "❤️",
    price: 800,
    effect: "Hồi 200 HP",
    desc: "Khôi phục thương thế nhanh.",
    heal: 200,
  },

  "cao-cap-hoi-huyet-dan": {
    type: "dan",
    name: "Thượng Phẩm Hồi Huyết Đan",
    emoji: "💖",
    price: 2500,
    effect: "Hồi 600 HP",
    desc: "Đan dược cực phẩm.",
    heal: 600,
  },

  "than-sinh-dan": {
    type: "dan",
    name: "Thần Sinh Đan",
    emoji: "✨",
    price: 10000,
    effect: "Hồi đầy HP",
    desc: "Khôi phục toàn bộ sinh lực.",
    healPercent: 100,
  },

  // VŨ KHÍ & PHÒNG CỤ (type: trang-bi)
  "moc-kiem": {
    type: "trang-bi",
    name: "Mộc Kiếm",
    emoji: "🗡️",
    price: 100,
    effect: "+2 Sức mạnh",
    stats: { power: 2 },
  },
  "thiet-kiem": {
    type: "trang-bi",
    name: "Thiết Kiếm",
    emoji: "⚔️",
    price: 300,
    effect: "+7 Sức mạnh",
    stats: { power: 7 },
  },
  "huyet-dao": {
    type: "trang-bi",
    name: "Huyết Đao",
    emoji: "🔪",
    price: 1500,
    effect: "+25 Sức, -5 Mị",
    stats: { power: 25, charisma: -5 },
  },
  "ao-vai": {
    type: "trang-bi",
    name: "Áo Vải",
    emoji: "👕",
    price: 80,
    effect: "+2 Phòng thủ",
    stats: { defense: 2 },
  },
  "thiet-giap": {
    type: "trang-bi",
    name: "Thiết Giáp",
    emoji: "🛡️",
    price: 300,
    effect: "+8 Phòng thủ",
    stats: { defense: 8 },
  },
  "hoa-long-giap": {
    type: "trang-bi",
    name: "Hỏa Long Giáp",
    emoji: "🐉",
    price: 2500,
    effect: "+50 Phòng thủ",
    stats: { defense: 50 },
  },
  "huyen-kiem": {
    type: "trang-bi",
    name: "Huyền Kiếm",
    emoji: "🗡️",
    price: 1200,
    effect: "+18 Sức mạnh",
    stats: { power: 18 },
  },

  "bach-ngoc-kiem": {
    type: "trang-bi",
    name: "Bạch Ngọc Kiếm",
    emoji: "⚔️",
    price: 2500,
    effect: "+35 Sức mạnh",
    stats: { power: 35 },
  },

  "sat-than-kiem": {
    type: "trang-bi",
    name: "Sát Thần Kiếm",
    emoji: "🩸",
    price: 12000,
    effect: "+90 Sức",
    stats: { power: 90 },
  },

  "thien-ma-kiem": {
    type: "trang-bi",
    name: "Thiên Ma Kiếm",
    emoji: "😈",
    price: 35000,
    effect: "+180 Sức",
    stats: { power: 180 },
  },

  "thien-de-kiem": {
    type: "trang-bi",
    name: "Thiên Đế Kiếm",
    emoji: "👑",
    price: 80000,
    effect: "+350 Sức",
    stats: { power: 350 },
  },

  "huyen-giap": {
    type: "trang-bi",
    name: "Huyền Giáp",
    emoji: "🛡️",
    price: 1500,
    effect: "+20 Thủ",
    stats: { defense: 20 },
  },

  "bach-ngoc-giap": {
    type: "trang-bi",
    name: "Bạch Ngọc Giáp",
    emoji: "🤍",
    price: 5000,
    effect: "+45 Thủ",
    stats: { defense: 45 },
  },

  "than-long-giap": {
    type: "trang-bi",
    name: "Thần Long Giáp",
    emoji: "🐲",
    price: 25000,
    effect: "+120 Thủ",
    stats: { defense: 120 },
  },

  "phi-phong-gio": {
    type: "trang-bi",
    name: "Phi Phong Gió",
    emoji: "🪽",
    price: 4000,
    effect: "+20 Thân pháp",
    stats: { agility: 20 },
  },

  "giay-than-hanh": {
    type: "trang-bi",
    name: "Giày Thần Hành",
    emoji: "🥾",
    price: 6000,
    effect: "+35 Thân pháp",
    stats: { agility: 35 },
  },

  "nhan-thien-menh": {
    type: "trang-bi",
    name: "Nhẫn Thiên Mệnh",
    emoji: "💍",
    price: 8000,
    effect: "+15 May mắn",
    stats: { luck: 15 },
  },

  "ngoc-boi-cuu-thien": {
    type: "trang-bi",
    name: "Ngọc Bội Cửu Thiên",
    emoji: "📿",
    price: 12000,
    effect: "+25 May",
    stats: { luck: 25 },
  },

  "linh-phu": {
    type: "trang-bi",
    name: "Linh Phù",
    emoji: "🧧",
    price: 80000,
    effect: "+8% Ngộ đạo",
    stats: { xpRate: 8 },
  },

  "than-phu": {
    type: "trang-bi",
    name: "Thần Phù",
    emoji: "📜",
    price: 18000,
    effect: "+20% Ngộ đạo",
    stats: { xpRate: 20 },
  },

  "dao-thach": {
    type: "trang-bi",
    name: "Đạo Thạch",
    emoji: "🪨",
    price: 30000,
    effect: "+35% Ngộ đạo",
    stats: { xpRate: 35 },
  },

  "dao-tam": {
    type: "trang-bi",
    name: "Đạo Tâm",
    emoji: "❤️",
    price: 25000,
    effect: "+5000 XP",
    stats: { xp: 5000 },
  },

  "hon-thien-an": {
    type: "trang-bi",
    name: "Hỗn Thiên Ấn",
    emoji: "☯️",
    price: 50000,
    effect: "+120 Sức,+80 Thủ",
    stats: { power: 120, defense: 80 },
  },

  "long-chau": {
    type: "trang-bi",
    name: "Long Châu",
    emoji: "🔵",
    price: 70000,
    effect: "+50 May,+50 Linh khí",
    stats: { luck: 50, linhKhi: 50 },
  },

  "than-ngoc": {
    type: "trang-bi",
    name: "Thần Ngọc",
    emoji: "💠",
    price: 90000,
    effect: "+100 Linh khí,+40 May",
    stats: { linhKhi: 100, luck: 40 },
  },

  "vo-thuong-chi-nhan": {
    type: "trang-bi",
    name: "Vô Thượng Chi Nhẫn",
    emoji: "💍",
    price: 150000,
    effect: "+100 Sức,+100 Thủ,+20% XP",
    stats: { power: 100, defense: 100, xpRate: 20 },
  },

  // CÔNG PHÁP & BÍ KÍP (type: cong-phap)
  "truong-xuan-cong": {
    type: "cong-phap",
    name: "Trường Xuân Công",
    emoji: "📜",
    price: 3000,
    effect: "Học để được: +20 HP, +5 Thủ",
    desc: "Tâm pháp cơ bản, sống dai như đỉa.",
    stats: { hp_bonus: 20, defense: 5 },
  },
  "cuu-duong-than-cong": {
    type: "cong-phap",
    name: "Cửu Dương Thần Công",
    emoji: "🔥",
    price: 8000,
    effect: "Học để được: +50 Sức, +20 Thủ",
    desc: "Chí dương chí cương, lực phá thiên quân.",
    stats: { hp_bonus: 50, power: 50, defense: 20 },
  },
  "lang-ba-vi-bo": {
    type: "cong-phap",
    name: "Lăng Ba Vi Bộ",
    emoji: "👣",
    price: 10000,
    effect: "Học để được: +40 Thân pháp (Né PK tốt)",
    desc: "Khinh công đệ nhất, không ai đánh trúng.",
    stats: { agility: 40, luck: 10 },
  },
  "thai-cuc-tam-kinh": {
    type: "cong-phap",
    name: "Thái Cực Tâm Kinh",
    emoji: "☯️",
    price: 3500,
    effect: "Học để được: +20 HP, +8 Thủ",
    desc: "Nội công ôn hòa, công thủ đều vững.",
    stats: { hp_bonus: 20, defense: 8 },
  },
  "hong-mong-cong": {
    type: "cong-phap",
    name: "Hồng Mông Công",
    emoji: "🌌",
    price: 4500,
    effect: "Học để được: +15 Linh khí, +10 May mắn",
    desc: "Hơi thở sơ khai của trời đất, tích tụ cực nhanh.",
    stats: { linhKhi: 15, luck: 10 },
  },
  "huyen-thien-cong": {
    type: "cong-phap",
    name: "Huyền Thiên Công",
    emoji: "🪐",
    price: 7000,
    effect: "Học để được: +20 Sức, +10 Thủ",
    desc: "Công pháp trung hậu, tăng lực chiến ổn định.",
    stats: { power: 20, defense: 10 },
  },
  "thien-ma-quyet": {
    type: "cong-phap",
    name: "Thiên Ma Quyết",
    emoji: "😈",
    price: 9500,
    effect: "Học để được: +30 Sức, -3 May mắn",
    desc: "Lực bùng nổ mạnh nhưng khí tức khá tà.",
    stats: { power: 30, luck: -3 },
  },
  "van-kiem-quyet": {
    type: "cong-phap",
    name: "Vạn Kiếm Quyết",
    emoji: "🗡️",
    price: 12000,
    effect: "Học để được: +40 Sức, +10 Thân pháp",
    desc: "Kiếm ý chồng chất, càng đánh càng bén.",
    stats: { power: 40, agility: 10 },
  },
  "cuu-chuyen-kim-than": {
    type: "cong-phap",
    name: "Cửu Chuyển Kim Thân",
    emoji: "🪨",
    price: 15000,
    effect: "Học để được: +50 HP, +25 Thủ",
    desc: "Rèn thể xác cứng như kim thạch.",
    stats: { hp_bonus: 50, defense: 25 },
  },
  "phuong-hoang-niet-ban": {
    type: "cong-phap",
    name: "Phượng Hoàng Niết Bàn",
    emoji: "🔥",
    price: 18000,
    effect: "Học để được: +60 HP, +15 May mắn",
    desc: "Tái sinh mạnh mẽ sau mỗi lần vượt ải.",
    stats: { hp_bonus: 60, luck: 15 },
  },
  "hu-khong-bo": {
    type: "cong-phap",
    name: "Hư Không Bộ",
    emoji: "👣",
    price: 11000,
    effect: "Học để được: +35 Thân pháp",
    desc: "Bước đi mờ ảo, né đòn rất tốt.",
    stats: { agility: 35 },
  },
  "hai-thuong-cong": {
    type: "cong-phap",
    name: "Hải Thượng Công",
    emoji: "🌊",
    price: 6000,
    effect: "Học để được: +25 Linh khí",
    desc: "Nội tức trầm ổn như sóng biển.",
    stats: { linhKhi: 25 },
  },
  "bat-cuc-quyen": {
    type: "cong-phap",
    name: "Bát Cực Quyền",
    emoji: "👊",
    price: 8000,
    effect: "Học để được: +25 Sức, +10 HP",
    desc: "Cương quyền trực diện, đánh rất lực.",
    stats: { power: 25, hp_bonus: 10 },
  },
  "luc-ma-cong": {
    type: "cong-phap",
    name: "Lục Mạch Công",
    emoji: "💠",
    price: 14000,
    effect: "Học để được: +20 Linh khí, +15 Sức",
    desc: "Chân nguyên lưu chuyển nhanh, sát thương ổn.",
    stats: { linhKhi: 20, power: 15 },
  },
  "thien-van-kinh": {
    type: "cong-phap",
    name: "Thiên Vận Kinh",
    emoji: "🍀",
    price: 16000,
    effect: "Học để được: +25 May mắn, +10 XP rate",
    desc: "Khí vận tăng mạnh, dễ gặp cơ duyên.",
    stats: { luck: 25, xpRate: 10 },
  },
  "van-phap-qui-nhat": {
    type: "cong-phap",
    name: "Vạn Pháp Quy Nhất",
    emoji: "📜",
    price: 22000,
    effect: "Học để được: +30 Sức, +30 Thủ, +15 Linh khí",
    desc: "Tổng hợp tinh hoa nhiều đường tu luyện.",
    stats: { power: 30, defense: 30, linhKhi: 15 },
  },
  "de-kinh": {
    type: "cong-phap",
    name: "Đế Kinh",
    emoji: "👑",
    price: 30000,
    effect: "Học để được: +50 Sức, +25 Thủ, +20 May",
    desc: "Công pháp đế vương, khí thế áp người.",
    stats: { power: 50, defense: 25, luck: 20 },
  },
  "tien-thien-dao-dien": {
    type: "cong-phap",
    name: "Tiên Thiên Đạo Điển",
    emoji: "🪷",
    price: 400000,
    effect: "Học để được: +50 Linh khí, +2 XP rate",
    desc: "Tăng tốc ngộ đạo, hợp cho giai đoạn tu hành dài.",
    stats: { linhKhi: 50, xpRate: 20 },
  },
  "hong-hoang-than-quyet": {
    type: "cong-phap",
    name: "Hồng Hoang Thần Quyết",
    emoji: "🌋",
    price: 50000,
    effect: "Học để được: +80 Sức, +40 HP",
    desc: "Khí lực cuồn cuộn, sát phạt cực mạnh.",
    stats: { power: 80, hp_bonus: 40 },
  },
  "vinh-hang-dao-kinh": {
    type: "cong-phap",
    name: "Vĩnh Hằng Đạo Kinh",
    emoji: "♾️",
    price: 65000,
    effect: "Học để được: +60 Thủ, +30 May mắn, +20 XP",
    desc: "Bền bỉ và bạo phát cân bằng.",
    stats: { defense: 60, luck: 30, xp: 2000 },
  },
  "thien-dao-chan-giai": {
    type: "cong-phap",
    name: "Thiên Đạo Chân Giải",
    emoji: "🌠",
    price: 80000,
    effect: "Học để được: +40% Ngộ đạo",
    desc: "Đại thành giúp tăng tốc độ tích lũy kinh nghiệm.",
    stats: { xpRate: 40 },
  },
  "khai-thien-dao-kinh": {
    type: "cong-phap",
    name: "Khai Thiên Đạo Kinh",
    emoji: "🌀",
    price: 1200000,
    effect: "Học để được: +80% Ngộ đạo, +50000 XP",
    desc: "Cực phẩm công pháp, mở đầu cho đại đạo chi lộ.",
    stats: { xpRate: 80, xp: 50000 },
  },
  "tam-tai-kiem-kinh": {
    type: "cong-phap",
    name: "Tam Tai Kiếm Kinh",
    emoji: "⚡",
    price: 26000,
    effect: "Học để được: +35 Sức, +20 Thân pháp",
    desc: "Kiếm pháp biến ảo, chém nhanh rút gọn.",
    stats: { power: 35, agility: 20 },
  },
  "thap-phuong-than-cong": {
    type: "cong-phap",
    name: "Thập Phương Thần Công",
    emoji: "✴️",
    price: 55000,
    effect: "Học để được: +40 Sức, +40 Thủ, +10 May mắn",
    desc: "Công pháp toàn diện, rất hợp endgame.",
    stats: { power: 40, defense: 40, luck: 10 },
  },

  // NÔNG NGHIỆP & KHÁC (type: khac)
  "hat-giong-thuong": {
    type: "khac",
    name: "Hạt Giống Lúa Mì",
    emoji: "🌾",
    price: 50,
    effect: "Trồng tại Nông Trại (/farm)",
    desc: "Hạt giống mọc ra Thảo Dược cơ bản.",
  },
  "hat-giong-hiem": {
    type: "khac",
    name: "Hạt Giống Huyết Sâm",
    emoji: "🩸",
    price: 300,
    effect: "Trồng tại Nông Trại (/farm)",
    desc: "Cho ra loại dược thảo quý hiếm.",
  },
  "can-cau": {
    type: "khac",
    name: "Cần Câu Trúc",
    emoji: "🎣",
    price: 150,
    effect: "Dùng để /cauca",
    desc: "Vật dụng thiết yếu để thả mồi câu.",
  },
  // ===== KHÁC (20) =====
  "phan-bon-linh-khi": {
    type: "khac",
    name: "Phân Bón Linh Khí",
    emoji: "🌱",
    price: 120,
    effect: "Dùng cho /farm: tăng năng suất",
    desc: "Giúp cây lớn nhanh và cho thu hoạch tốt hơn.",
    stats: { farmSpeed: 5 },
  },
  "phan-bon-tien-pham": {
    type: "khac",
    name: "Phân Bón Tiên Phẩm",
    emoji: "🌾",
    price: 400,
    effect: "Dùng cho /farm: tăng năng suất lớn",
    desc: "Phân bón cao cấp dành cho dược thảo quý.",
    stats: { farmSpeed: 12 },
  },
  "binh-tuoi-than": {
    type: "khac",
    name: "Bình Tưới Thần",
    emoji: "💧",
    price: 300,
    effect: "Dùng cho /farm: tăng tốc trồng",
    desc: "Tưới một lần, cây lên xanh rất nhanh.",
    stats: { farmSpeed: 8 },
  },
  "cuoc-huyen-thiet": {
    type: "khac",
    name: "Cuốc Huyền Thiết",
    emoji: "⛏️",
    price: 600,
    effect: "Dùng cho /farm: tăng tốc độ canh tác",
    desc: "Làm đất nhanh, ít tốn sức.",
    stats: { farmSpeed: 10 },
  },
  "cuoc-tien-khi": {
    type: "khac",
    name: "Cuốc Tiên Khí",
    emoji: "⚒️",
    price: 1800,
    effect: "Dùng cho /farm: tăng mạnh năng suất",
    desc: "Dụng cụ canh tác cấp cao.",
    stats: { farmSpeed: 20 },
  },
  "hat-giong-linh-chi": {
    type: "khac",
    name: "Hạt Giống Linh Chi",
    emoji: "🍄",
    price: 350,
    effect: "Trồng tại /farm",
    desc: "Cho ra dược liệu linh chi phổ biến.",
  },
  "hat-giong-thien-son-tuyet-lien": {
    type: "khac",
    name: "Hạt Giống Thiên Sơn Tuyết Liên",
    emoji: "❄️",
    price: 1200,
    effect: "Trồng tại /farm",
    desc: "Dược thảo quý, giá trị cao.",
  },
  "hat-giong-cuu-diep-linh-chi": {
    type: "khac",
    name: "Hạt Giống Cửu Diệp Linh Chi",
    emoji: "🍃",
    price: 2200,
    effect: "Trồng tại /farm",
    desc: "Dược thảo thượng phẩm, hiếm gặp.",
  },
  "hat-giong-bat-tu-thao": {
    type: "khac",
    name: "Hạt Giống Bất Tử Thảo",
    emoji: "🌿",
    price: 5000,
    effect: "Trồng tại /farm",
    desc: "Cho ra thảo dược dùng để luyện đan cao cấp.",
  },
  "ve-bi-canh": {
    type: "khac",
    name: "Vé Bí Cảnh",
    emoji: "🎫",
    price: 2500,
    effect: "Mở lượt vào bí cảnh",
    desc: "Dùng để tham gia phụ bản đặc biệt.",
  },
  "chia-khoa-bi-canh": {
    type: "khac",
    name: "Chìa Khóa Bí Cảnh",
    emoji: "🗝️",
    price: 8000,
    effect: "Mở rương / cửa bí cảnh",
    desc: "Chìa khóa đặc biệt cho khu vực ẩn.",
  },
  "da-cuong-hoa": {
    type: "khac",
    name: "Đá Cường Hóa",
    emoji: "💎",
    price: 1500,
    effect: "Cường hóa trang bị",
    desc: "Vật liệu nâng cấp vũ khí và giáp.",
  },
  "da-kham": {
    type: "khac",
    name: "Đá Khảm",
    emoji: "🔷",
    price: 2200,
    effect: "Khảm ngọc vào trang bị",
    desc: "Dùng để gắn thuộc tính đặc biệt.",
  },
  "da-tay-luyen": {
    type: "khac",
    name: "Đá Tẩy Luyện",
    emoji: "🪄",
    price: 3200,
    effect: "Tẩy lại chỉ số trang bị",
    desc: "Giúp roll lại dòng thuộc tính.",
  },
  "ve-reset-thuoc-tinh": {
    type: "khac",
    name: "Vé Reset Thuộc Tính",
    emoji: "♻️",
    price: 10000,
    effect: "Reset điểm chỉ số",
    desc: "Dùng để phân bổ lại điểm thuộc tính.",
  },
  "ve-nhan-doi-xp": {
    type: "khac",
    name: "Vé Nhân Đôi XP",
    emoji: "2️⃣",
    price: 20000000,
    effect: "+100% Ngộ đạo vĩnh viễn",
    desc: "Tăng tốc nhận kinh nghiệm trong thời gian giới hạn.",
    stats: { xpRate: 100 },
  },
  "linh-phu-may-man": {
    type: "khac",
    name: "Linh Phù May Mắn",
    emoji: "🧧",
    price: 5000,
    effect: "+15 May mắn",
    desc: "Bùa mang lại vận khí tốt hơn.",
    stats: { luck: 15 },
  },
  "the-nghiem-tien-vao": {
    type: "khac",
    name: "Thẻ Nghiệm Tiên",
    emoji: "🪪",
    price: 15000,
    effect: "+15000 XP",
    desc: "Dùng một lần để tăng XP tức thời.",
    stats: { xp: 15000 },
  },
  "thach-ngoc-ngo-dao": {
    type: "khac",
    name: "Thạch Ngọc Ngộ Đạo",
    emoji: "🧠",
    price: 250000,
    effect: "+25% Ngộ đạo",
    desc: "Vật phẩm hỗ trợ tu luyện rất mạnh.",
    stats: { xpRate: 25 },
  },
};

const SCENARIOS = {
  work: [
    "Bưng bê đan dược chạy sml ở Tụ Bảo Các",
    "Quét rác ở quảng trường Tông môn đến trật cả lưng",
    "Cho Linh Hạc ăn bị nó mổ sưng đầu",
    "Làm hộ vệ đi tiêu cho đám phàm nhân",
    "Chép phạt tâm pháp trong Tàng Kinh Các",
    "Đi giao bùa chú bị khách bom hàng",
    "Khiêng bao linh thạch nặng muốn gãy tay",
    "Mài kiếm cho trưởng lão tới tóe lửa",
    "Hầu trà cho khách quý bị sai một ly là ăn mắng",
    "Dọn chuồng yêu thú, vừa hôi vừa mệt",
    "Phân loại linh dược đến hoa cả mắt",
    "Sửa lại hàng rào tông môn bị gió thổi đổ",
    "Khiêng đá lát đường từ sáng tới tối",
    "Xách nước lên đỉnh núi cho ngoại môn",
    "Canh cổng tông môn cả ngày không được ngồi",
    "Đếm linh thạch kho đến khô cả cổ",
    "Gói bọc đan dược đến đau cả ngón tay",
    "Rửa nồi luyện đan dính đầy cặn cháy",
    "Lau sàn đại điện sáng loáng như soi gương",
    "Thu gom lá rụng trong sân luyện công",
    "Chuyển hàng cho kho vật tư bị lạc đường giữa núi",
    "Khắc bảng thông báo đến mỏi cả mắt",
    "Thay ngói mái nhà cho đệ tử nội môn",
    "Sửa chuông báo thức của tông môn bị hỏng",
    "Làm sổ sách nhiệm vụ đến hoa mắt chóng mặt",
    "Phơi thảo dược giữa trưa nắng muốn bốc khói",
    "Dọn đá vụn sau một trận tỷ thí nát sân",
    "Quét mạng nhện trong kho cũ âm u",
    "Giữ kho lương thực không cho chuột yêu vào",
    "Khuân đá xây tường bao quanh sơn môn",
    "Trông lò luyện khí suốt canh giờ không dám chợp mắt",
    "Đánh bóng chuôi kiếm cho khách đặt hàng",
    "Sắp xếp thư tín tông môn ngập cả bàn",
    "Dắt linh thú đi tản bộ đến muốn tụt hơi",
    "Tỉa cỏ ở vườn thuốc cả buổi không xong",
    "Sửa bảng trận pháp ngoài sân bị lệch một góc",
    "Canh bếp nấu cám cho linh cầm bị khét nồi",
    "Gánh gỗ về dựng nhà kho mới",
    "Lau sạch vết bùn ở hành lang sau mưa lớn",
    "Thu mua hàng từ chợ linh vật về kho",
    "Đóng gói pháp khí gửi cho khách ở xa",
    "Phân phát cơm canh cho đệ tử ngoại môn",
    "Gỡ bẫy thú trong rừng sau nhiệm vụ",
    "Canh mộ địa của tổ sư suốt đêm",
    "Nhặt đá cuội ở suối để lát đường",
    "Đổi linh thạch lẻ cho cả đống đệ tử càu nhàu",
    "Sửa lại cửa gỗ bị lệch bản lề",
    "Ghi danh người vào tông môn đến tê tay",
    "Quét sạch sân sau khi diễn võ xong",
    "Trông quầy bán bùa đến khản cả cổ",
  ],

  mine: [
    "Đào trúng tổ kiến lửa linh tinh, cắn sưng mông nhưng nhặt được khoáng thạch",
    "Bổ cuốc chói lửa, lòi ra một viên linh thạch lấp lánh",
    "Đào sập cả một góc hang, mém chết nhưng vớ được quặng hiếm",
    "Tìm thấy một khe nứt chứa tinh thể khoáng sản lấp lánh",
    "Đập vỡ lớp đá cứng như thép, bên trong có mạch quặng vàng óng",
    "Đào sâu xuống lòng đất, phát hiện một viên ngọc khoáng kỳ dị",
    "Bị đất đá rơi trúng đầu nhưng moi ra được cục thiết tinh",
    "Đụng phải hang dơi quỷ, đánh nhau xong thu được khoáng mạch tốt",
    "Đào đến hụt hơi thì thấy một đường mạch linh thiết chạy dài",
    "Khui một phiến đá cổ, phía trong ẩn một lớp tinh quặng sáng rực",
    "Bổ nhát cuối cùng làm bật ra viên huyền thiết quý giá",
    "Đào nhầm ổ sâu đất, bị cắn te tua nhưng nhặt được ngọc thạch",
    "Dò khí sai một bước, suýt lạc hang nhưng lại gặp mỏ bạc linh",
    "Bắt gặp dòng nước ngầm cuốn ra vài hạt sa kim quý",
    "Đào xuyên qua lớp quặng vụn, tìm thấy lõi tinh khoáng",
    "Lỡ chạm bẫy đá rơi, may mà ôm được túi quặng hiếm",
    "Xới đất lên mới biết phía dưới là mạch hàn thiết",
    "Bửa đá đến nứt cuốc, may còn moi ra được cục linh thạch lớn",
    "Đào trong vách núi trơn trượt rồi rớt xuống hố quặng",
    "Phát hiện hang động nhỏ chứa đầy mảnh khoáng phát sáng",
    "Bổ cuốc lệch tay, đập trúng lớp đá rỗng có quặng tím",
    "Đào trúng tổ ong đá, bị ong đuổi nhưng lấy được ngọc tinh",
    "Lần theo ánh sáng yếu ớt, tìm thấy mạch khoáng sâu dưới đất",
    "Mở lối qua tảng đá chắn đường, gặp túi quặng chưa ai chạm",
    "Đào lún cả người xuống bùn khoáng nhưng kéo lên được thiết sa",
    "Cuốc vỡ cán nhưng đổi lại có một mảnh thiên thạch nhỏ",
    "Đào vào vùng đá nóng, nóng ran da thịt nhưng nhặt được hỏa tinh",
    "Thấy vết nứt trên vách, moi ra một ổ tinh thạch kết tụ",
    "Đập đá theo tiếng vọng, phát hiện hang quặng rỗng bên trong",
    "Khai quật lớp đất cổ, lộ ra mạch khoáng bị chôn ngàn năm",
    "Đào ngay chỗ tưởng vô ích, hóa ra có cục linh sa ẩn sâu",
    "Chạm phải khí lạnh từ lòng đất nhưng tìm ra hàn ngọc",
    "Đào qua tầng đá vụn, phát hiện một đĩa khoáng hiếm",
    "Bị đá lăn truy đuổi, chạy một đoạn rồi vớ được mạch quặng tốt",
    "Xốc cuốc lên phá vỡ tảng đá đen, bên trong có tinh thiết",
    "Đào trong hang hẹp đến nghẹt thở, cuối cùng lôi ra một khối ngọc khoáng",
    "Phát hiện đường hầm cũ của ai đó, bên trong còn sót quặng quý",
    "Đào trúng nền đá phát sáng, thu được khoáng thạch lạ",
    "Bổ vỡ lớp đá ngoài cùng, bên trong là mạch huyền kim",
    "Lội qua bùn đất trơn trượt rồi nhặt được quặng tinh sạch",
    "Đào hụt một nhát làm sập trần hang, nhưng lộ ra mạch lớn",
    "Bị khói bụi mù mắt, song tìm được sa tinh dưới chân",
    "Đào tới lớp đá cổ xám đen, lộ ra vài viên linh khoáng",
    "Móc sâu vào lòng núi, phát hiện một cụm thạch tinh",
    "Cào lớp đất mỏng, bất ngờ gặp mạch bạc quặng",
    "Đào qua khe núi chật, thấy hố quặng bị bỏ quên",
    "Bửa mở mặt đá lạnh, thu về một viên hàn thiết hiếm",
    "Mò mãi trong bụi đất cuối cùng cũng nhặt được ngọc quặng",
    "Đào đúng chỗ đất sụt, tưởng toi nhưng lại lộ mạch khoáng cực ngon",
  ],

  fish: [
    "Câu được một con Cá Chép Linh Khí béo múp",
    "Giật mạnh cần, dính ngay một con Rùa Đá 100 tuổi",
    "Mồi bị cá rỉa sạch, nhưng vô tình vớt được rương rác có linh thạch",
    "Câu trúng một con Thủy Quái nhỏ, đánh một trận tơi bời mới bắt được",
    "Kéo lên một con cá bạc to như cái nia",
    "Cần rung dữ dội, kéo ra một con cá sừng đỏ ngầu",
    "Bắt được một con cá phát sáng trong đêm",
    "Móc câu dính vào lùm rong, lôi lên cả bầy cá con",
    "Thả mồi xuống chưa lâu đã dính ngay cá linh",
    "Kéo cần mãi tưởng hụt, cuối cùng câu được cá chép vàng",
    "Cá cắn câu rồi quẫy mạnh làm ướt cả người",
    "Vớ được một con cá trê đá nặng trịch",
    "Câu trúng một con cá đuôi dài có vảy ánh tím",
    "Kéo lên một con cua linh kẹp gãy lưỡi câu",
    "Mồi chìm xuống đáy, kéo lên lại được một viên ngọc nước",
    "Dính phải cá dữ, bị nó lôi đi một đoạn mới giữ được dây",
    "Câu được một con cá mắt đỏ, nhìn phát thấy lạnh gáy",
    "Tung mồi chuẩn xác, vớ ngay cá linh bơi ngược dòng",
    "Móc câu mắc vào đáy sông nhưng lôi ra được túi bảo vật",
    "Cá nhảy khỏi mặt nước, đập bốp vào thuyền rồi rơi lại xuống",
    "Bắt được một con cá nhỏ nhưng trong bụng có hạt linh châu",
    "Kéo lên một con cá mập nước ngọt hung dữ",
    "Cần câu nặng bất thường, hóa ra là một con rùa linh",
    "Thả mồi ở khúc nước sâu, câu được cá trắng như ngọc",
    "Câu trúng một con cá mũi dài chuyên cướp mồi",
    "Bị cá quẫy làm đứt một sợi dây câu, nhưng vẫn giữ được con mồi",
    "Kéo lên một con cá có vây như lưỡi kiếm",
    "Câu được một con cá thần đèn bé tí",
    "Mồi bị nuốt mất, lôi lên mới biết dính phải cá yêu",
    "Bắt được một con cá có vảy phản chiếu ánh trăng",
    "Câu trúng một con tôm linh đỏ au to như bàn tay",
    "Kéo lên một con cá bống đá cứng ngắc",
    "Dây câu giật bắn, lôi ra một con cá trân châu",
    "Câu được cá linh nhảy tanh tách trên mạn thuyền",
    "Mồi thả xuống gặp ngay đàn cá tranh ăn hỗn loạn",
    "Kéo lên một con cá đuôi lửa bốc hơi nóng",
    "Giật cần đúng lúc, bắt trúng cá vàng may mắn",
    "Câu trúng một con cá to đến nỗi phải ôm bằng hai tay",
    "Bắt được một con cá da xanh bóng như ngọc",
    "Mồi bị kéo tuột xuống đáy, cuối cùng vớt lên được cá quý",
    "Câu vào bầy cá nhỏ nhưng lọc ra được một con cá chúa",
    "Kéo lên một con cá mắt vàng nhìn cực kỳ ngơ",
    "Dính câu một con cá nhe răng dữ tợn",
    "Thả mồi vào xoáy nước, câu được cá xoáy vân hiếm",
    "Kéo lên một con cá dài như dải lụa",
    "Câu trúng cá linh nhảy cao, suýt quăng luôn cần",
    "Bắt được một con cá có mùi thơm lạ lùng",
    "Móc câu lấp ló trong nước, kéo lên một rương gỗ cũ",
    "Câu được một con cá chép hóa rồng còn non",
    "Kéo lên một con cá thần nhỏ đang ngủ gật",
  ],

  pk_win: [
    "tung một chưởng Diệt Thế ấn trúng giữa ngực",
    "thi triển Tật Phong Bộ áp sát, đá văng",
    "dùng tu vi áp đảo, quát một tiếng làm",
    "vung kiếm chém ngang khiến đối thủ",
    "đánh ra một quyền long hổ làm",
    "đập một chưởng vào vai khiến đối thủ",
    "lách người né chiêu rồi phản kích làm",
    "vận công phá thế, ép cho đối thủ",
    "tụ linh lực vào tay, búng một cái làm",
    "phóng ra một đạo kiếm khí khiến đối thủ",
    "dậm chân một cái, khí thế bùng lên làm",
    "xoay người tung cước khiến đối thủ",
    "đổi chiêu cực nhanh, chặn đứng thế công của",
    "đánh bật pháp khí của",
    "dùng thân pháp quỷ mị áp sát khiến",
    "một tay bóp nát thế trận của",
    "khóa chặt yết hầu khí lực khiến",
    "thả ra uy áp làm",
    "đập thẳng một đòn chính diện khiến",
    "liên hoàn ba chiêu ép cho",
    "ném bùa nổ đúng lúc khiến",
    "chém một đường kiếm sáng rực làm",
    "vung thương quét ngang khiến",
    "đổi thế thủ sang công làm",
    "mở đại trận nhỏ chặn hết đường lui của",
    "dồn toàn lực một kích khiến",
    "một chiêu phá giáp đánh văng",
    "đấm thẳng vào bụng khiến",
    "kết ấn nhanh như chớp làm",
    "dùng tốc độ nghiền ép khiến",
    "phản đòn hiểm hóc khiến",
    "ném đối phương lăn mấy vòng rồi",
    "đánh cho vũ khí của",
    "phá tan thế đứng của",
    "đè bằng khí thế khiến",
    "tung liên tiếp mấy đòn làm",
    "một bước áp tới khiến",
    "quăng đối thủ ra khỏi vòng chiến rồi",
    "gọi ra linh thú hỗ trợ khiến",
    "đánh chặn đúng nhịp làm",
    "dồn đối thủ vào góc rồi",
    "một chiêu tàn nhẫn khiến",
    "dùng trận pháp trói chân làm",
    "xoáy tay bẻ hướng tấn công khiến",
    "tát lệch mặt khiến",
    "vung đao bổ xuống làm",
    "đánh ngã gục bằng một cú dứt điểm làm",
    "vừa né vừa phản công khiến",
    "đè bẹp trong vài nhịp thở làm",
    "bẻ gãy ý chí chiến đấu của",
  ],

  pk_lose: [
    "múa may xập xình rồi vấp cục đá đập mặt xuống đất, bị",
    "chưa kịp tung chiêu đã bị",
    "dùng sai công pháp, tẩu hỏa nhập ma hộc máu, liền bị",
    "lao vào quá hăng nên bị",
    "vung kiếm loạn xạ rồi tự mắc chân, bị",
    "đang gồng khí thế thì sơ ý trượt chân, bị",
    "ra chiêu quá chậm nên bị",
    "đổi tư thế sai nhịp, bị",
    "cố làm màu quá đà nên bị",
    "bấm ấn quyết nhầm, khí lực loạn lên rồi bị",
    "chưa nhìn rõ đường đã bị",
    "vừa xoay người thì bị",
    "đang định phản công thì bị",
    "mất thăng bằng sau một cú né hụt, bị",
    "hít phải bụi làm cay mắt rồi bị",
    "bị đối thủ áp sát quá nhanh, không kịp trở tay nên bị",
    "đỡ hụt một đòn, tay tê rần rồi bị",
    "cố cắn răng chịu đòn nhưng vẫn bị",
    "định ra tuyệt chiêu nhưng linh lực cạn sạch, bị",
    "bị đối thủ phá thế trận rồi bị",
    "đâm đầu vào chiêu hiểm của đối thủ nên bị",
    "vừa bước lên đã bị",
    "chạy loạn một hồi rồi bị",
    "tự làm rối bộ pháp, bị",
    "ném bùa lệch hướng nên bị",
    "quá tự tin khinh địch, cuối cùng bị",
    "đang tích lực thì bị",
    "bị dồn vào góc, chỉ biết đứng chịu",
    "vừa gào to thì bị",
    "bất cẩn để lộ sơ hở rồi bị",
    "đưa tay đỡ nhưng lực quá mạnh, bị",
    "cố kéo dài trận nhưng vẫn bị",
    "đi sai một bước, bị",
    "đang hò hét cổ vũ chính mình thì bị",
    "đánh hụt liên tiếp ba chiêu nên bị",
    "bị phản đòn ngay lúc mất tập trung, rồi bị",
    "vừa lao tới đã bị",
    "đứng hình trong một nhịp rồi bị",
    "đang định chạy trốn thì bị",
    "đổi vũ khí không kịp nên bị",
    "tự vướng áo choàng mà ngã, bị",
    "đang nghĩ mưu thì bị",
    "dồn lực sai chỗ làm cơ thể rối loạn rồi bị",
    "vừa mở miệng khiêu khích đã bị",
    "né được một đòn nhưng dính ngay đòn sau, bị",
    "hớ hênh lộ lưng, bị",
    "quá mệt nên động tác chậm hẳn, bị",
    "đang cố giữ thể diện thì bị",
    "vừa cất bước đã bị",
    "bị chặn sạch đường thoát, chỉ còn cách chịu",
    "đấu tới kiệt sức rồi bị",
    "ngẩng đầu lên một cái là bị",
  ],
};

const ACTION_TEXT = {
  daily: [
    "Hôm nay điểm danh ở Tông môn, bị trưởng lão nhìn một cái rồi đi luôn",
    "Đứng xếp hàng nhận điểm danh, suýt bị chen văng ra ngoài",
    "Lên danh sách sáng sớm, trời còn chưa kịp sáng hẳn",
    "Điểm danh xong, tiện tay quét luôn sân đá",
    "Đến đúng giờ, không bị gọi tên lần hai",
    "Xác nhận danh tịch, nhận phần thưởng từ chấp sự",
    "Điểm danh giữa sân lớn, ai nấy đều nhìn ngươi",
    "Ghé qua một vòng rồi quay về, cực kỳ trơn tru",
    "Nhận dấu điểm danh, hoàn thành nhiệm vụ ngày",
    "Sáng nay đến sớm, danh sách đóng dấu gọn gàng",
  ],
  quest: [
    "Gửi thư cho trưởng lão bị bắt quay lại 2 lần",
    "Khiêng đan lô suýt trượt chân xuống bậc đá",
    "Dọn kho linh thạch cho Tông môn",
    "Đi thu hồi đơn đặt hàng thất lạc",
    "Canh cổng tông môn nguyên một ca",
    "Chạy đi truyền tin khắp dãy điện",
    "Sắp xếp thẻ tre trong Tàng Kinh Các",
    "Sửa lại bảng nhiệm vụ bị gió thổi lệch",
    "Chuyển đồ đến kho phụ, đường xa muốn gãy chân",
    "Làm việc vặt cho chấp sự cả buổi",
  ],
  patrol: [
    "Tuần tra quanh sơn môn, phát hiện vài kẻ lén vặt cỏ linh",
    "Đi tuần đêm, bắt gặp một đám tiểu yêu bỏ chạy",
    "Lượn một vòng quanh linh mạch, ai cũng tưởng ngươi là cao thủ",
    "Đi dọc tường thành, tiện tay dập một đám gây rối",
    "Canh một đoạn đường núi, gió thổi rét cả vai",
    "Đi kiểm tra bùa hộ sơn, mọi thứ đều ổn",
    "Dò quanh ngoại viện, phát hiện dấu chân lạ",
    "Tuần một vòng sân lớn, không bỏ sót góc nào",
    "Đi tuần theo đội, xử lý nhanh một vụ lộn xộn",
    "Xác nhận khu vực bình an, báo cáo xong xuôi",
  ],
  delivery: [
    "Giao hàng xong, khách bo thêm tiền",
    "Chạy đơn xuyên qua mấy dãy núi",
    "Đưa vật phẩm tới nơi, không làm vỡ món nào",
    "Giao đúng hẹn, được thưởng thêm hậu hĩnh",
    "Chở hàng qua cửa đá, đường khá trơn",
    "Đem vật phẩm quý tới tay người nhận",
    "Tới nơi đúng lúc, bên kia trả thêm linh thạch",
    "Giao gói hàng niêm phong, không có sai sót",
    "Chạy một chuyến xa, khách hàng rất vừa ý",
    "Hoàn tất chuyển phát, nhận thêm tiền tip",
  ],
  hunt: [
    "Săn được một con thú linh nhỏ chạy xuyên bụi rậm",
    "Bẫy thú nổ đúng lúc, thu về chiến lợi phẩm",
    "Đuổi theo một con yêu thú non rồi tóm gọn",
    "Lần theo dấu chân giữa rừng, trúng mồi khá ngon",
    "Phục kích ở khe đá, săn được con mồi nhanh gọn",
    "Săn đêm ở bìa rừng, không tốn nhiều công sức",
    "Đặt bẫy trong bụi cỏ, con mồi tự chui vào",
    "Rượt đuổi một hồi rồi kết liễu gọn",
    "Đổi hướng cực nhanh, bắt sống con thú nhỏ",
    "Đi săn vòng ngoài, thu hoạch khá ổn",
  ],
  gather: [
    "Hái được dược thảo mọc ven vách núi",
    "Lục lọi khe đá nhặt được vài cục linh sa",
    "Tìm thấy một bụi thảo dược quý bị che trong cỏ dại",
    "Bẻ được vài nhánh linh thảo còn tươi",
    "Lội qua bụi rậm, gom được khá nhiều lá thuốc",
    "Nhặt thảo dược ở triền núi, mùi thơm rất đậm",
    "Phát hiện chỗ đất tốt, dược liệu mọc thành cụm",
    "Đào được ít linh căn non từ dưới đá",
    "Hái quanh suối linh, thu được hàng khá tốt",
    "Lượm đủ nguyên liệu về nộp cho môn phái",
  ],
  salvage: [
    "Nhặt được mảnh phế giáp còn dùng được",
    "Bới đống đồ cũ trong kho phế, may mắn vớ được linh kiện",
    "Lượm được một hộp gỗ mục nhưng bên trong vẫn còn đồ bán được",
    "Nhặt đồ cũ từ bãi phế liệu, kiếm được món còn giá trị",
    "Tách kim loại từ đống junk, bán lại cũng ra tiền",
    "Lục kho bỏ hoang, vớ được vài món xài tạm",
    "Nhặt được đống phụ kiện cũ nhưng vẫn có người mua",
    "Thu hồi đống phế, lọc ra món còn tốt",
    "Bới trong thùng hỏng, may không phí công",
    "Chọn lại đống đồ cũ, gom được món đem bán",
  ],
  escort: [
    "Hộ tống thương nhân an toàn qua đèo",
    "Đưa người đi đường vượt qua khu vực nhiều kẻ quấy rối",
    "Áp tải hàng hóa qua đoạn đường khó",
    "Hộ tống xong, thương nhân trả rất hậu",
    "Dẫn đoàn đi qua sơn đạo, xử lý êm",
    "Canh bên cạnh xe hàng suốt quãng đường",
    "Giữ an toàn cho đội hộ tống, không phát sinh chuyện lớn",
    "Đưa khách qua trạm kiểm soát an toàn",
    "Đi cùng đoàn suốt tuyến, phần thưởng khá cao",
    "Hoàn thành hộ tống, cả hai bên đều hài lòng",
  ],
  trade: [
    "Bắt đúng nhịp thị trường, lướt sóng cực đẹp",
    "Mua bán có lãi nhẹ",
    "Giao dịch xong, lời không nhiều nhưng ổn",
    "Đổi hàng rất trơn tru, gặp đúng người cần",
    "Bán đúng lúc giá lên, thu về khá tốt",
    "Mua rẻ bán vừa, lời đều đều",
    "Chốt deal nhanh gọn, không bị ép giá",
    "Lượm được món dễ bán, xoay vòng vốn tốt",
    "Nghe ngóng thị trường chuẩn, kiếm được chút đỉnh",
    "Giao dịch ổn định, có lời sạch",
  ],
  pray: [
    "Tĩnh tâm cầu phúc, khí vận hơi khởi sắc",
    "Khấn nguyện trước linh tượng, cảm giác nhẹ người",
    "Thắp hương cầu lộc, tâm thần yên ổn",
    "Ngồi thiền một lúc rồi thử cầu may",
    "Cầu phúc trong yên lặng, linh khí quanh người hơi động",
    "Đọc chú nguyện ngắn, vận khí có vẻ sáng hơn",
    "Lạy trước pháp đàn, mong được thêm chút may",
    "Thành tâm cầu xin, trời đất có vẻ nghe thấy",
    "Ngồi dưới đèn linh, tâm trạng ổn định hẳn",
    "Cầu an xong, mọi thứ vẫn khá suôn sẻ",
  ],
};

const TREASURE_TABLE = [
  {
    weight: 50,
    title: "🪙 Nhặt được ít linh thạch vụn từ kẽ đá",
    money: [20, 80],
    xp: [8, 14],
  },
  {
    weight: 30,
    title: "💨 Chỉ moi ra mấy đồng tiền lẻ bị chôn",
    money: [30, 90],
    xp: [8, 15],
  },
  {
    weight: 10,
    title: "📦 Lôi ra một hòm gỗ cũ còn sót ít đồ bán được",
    money: [60, 140],
    xp: [10, 18],
    herb: [0, 1],
  },
  {
    weight: 10,
    title: "🗝️ Tìm thấy ngách đá nhỏ, bên trong có chút tài vật",
    money: [80, 180],
    xp: [10, 18],
    ore: [0, 1],
  },
  {
    weight: 10,
    title: "🧭 Nhặt được túi tiền rơi của tiền nhân",
    money: [100, 220],
    xp: [10, 20],
  },
  {
    weight: 9,
    title: "✨ Khai quật được rương nhỏ giấu dưới bụi cây",
    money: [120, 260],
    xp: [12, 22],
    herb: [1, 2],
  },
  {
    weight: 9,
    title: "🪨 Đập vỡ tảng đá, bên trong có khoáng vật có giá",
    money: [140, 280],
    xp: [12, 22],
    ore: [1, 2],
  },
  {
    weight: 8,
    title: "📜 Lấy được tàn quyển cũ và ít tài vật",
    money: [160, 320],
    xp: [12, 24],
  },
  {
    weight: 8,
    title: "🧴 Nhặt được bình thuốc cũ còn dùng được",
    money: [180, 340],
    xp: [14, 24],
    item: { id: "tieu-hoan-dan", qty: 1 },
  },
  {
    weight: 8,
    title: "🧪 Tìm thấy túi dược liệu hiếm",
    money: [180, 360],
    xp: [14, 24],
    item: { id: "hoi-khi-dan", qty: 1 },
  },
  {
    weight: 5,
    title: "💊 Đào trúng một bình linh đan tốt",
    money: [220, 420],
    xp: [15, 28],
    item: { id: "hoi-xuan-dan", qty: 1 },
  },
  {
    weight: 5,
    title: "🧿 Nhặt được một món phụ kiện tu luyện",
    money: [240, 460],
    xp: [15, 28],
    item: { id: "ngoc-phu-kien", qty: 1 },
  },
  {
    weight: 4,
    title: "⚔️ Tìm được một thanh kiếm thường nhưng còn dùng được",
    money: [260, 500],
    xp: [16, 30],
    item: { id: "thanh-kiem-co", qty: 1 },
  },
  {
    weight: 4,
    title: "🛡️ Lượm được một món giáp cũ nhưng chắc",
    money: [260, 520],
    xp: [16, 30],
    item: { id: "thiet-giap-co", qty: 1 },
  },
  {
    weight: 3,
    title: "🌟 Trúng rương có linh đan khá xịn",
    money: [320, 650],
    xp: [18, 35],
    item: { id: "dao-hoa-dan", qty: 1 },
  },
  {
    weight: 1,
    title: "🔥 Nhặt được vũ khí cấp khá cao",
    money: [340, 700],
    xp: [18, 35],
    item: { id: "phong-hoa-kiem", qty: 1 },
  },
  {
    weight: 0.2,
    title: "💠 Bảo hạp cổ, bên trong có linh đan và tài vật",
    money: [420, 850],
    xp: [20, 40],
    item: { id: "chan-nguyen-dan", qty: 1 },
  },
  {
    weight: 2,
    title: "🗡️ Trúng được pháp khí cực hiếm",
    money: [500, 1000],
    xp: [22, 45],
    item: { id: "huyet-nguyet-kiem", qty: 1 },
  },
  {
    weight: 0.01,
    title: "🌀 Đại cơ duyên! Nhặt được bảo vật cấp cao",
    money: [800, 1500],
    xp: [25, 55],
    item: { id: "cuu-linh-dan", qty: 1 },
  },
  {
    weight: 0.01,
    title: "🐉 Cổ mộ mở ra, rơi thẳng ra thần binh hiếm có",
    money: [1000, 2200],
    xp: [30, 70],
    item: { id: "than-long-kiem", qty: 1 },
  },
];

module.exports = {
  GAME_SHOP_ITEMS,
  CULTIVATION_REALMS,
  SCENARIOS,
  ACTION_TEXT,
  TREASURE_TABLE,
};
