import { CalculatorKey, SemanticAction } from "../types";

export const CALCULATOR_KEYS: CalculatorKey[] = [
  // --- Top Row Controls ---
  {
    id: "SHIFT",
    label: "SHIFT",
    colorType: "utility",
    action: { type: "TOGGLE_SHIFT" },
    ariaLabel: "Shift modifier",
  },
  {
    id: "ALPHA",
    label: "ALPHA",
    colorType: "utility",
    action: { type: "TOGGLE_ALPHA" },
    ariaLabel: "Alpha variable modifier",
  },
  {
    id: "UP",
    label: "▲",
    colorType: "utility",
    action: { type: "MOVE_CURSOR", direction: "UP" },
    ariaLabel: "Replay up",
  },
  {
    id: "LEFT",
    label: "◀",
    colorType: "utility",
    action: { type: "MOVE_CURSOR", direction: "LEFT" },
    ariaLabel: "Replay left",
  },
  {
    id: "RIGHT",
    label: "▶",
    colorType: "utility",
    action: { type: "MOVE_CURSOR", direction: "RIGHT" },
    ariaLabel: "Replay right",
  },
  {
    id: "DOWN",
    label: "▼",
    colorType: "utility",
    action: { type: "MOVE_CURSOR", direction: "DOWN" },
    ariaLabel: "Replay down",
  },
  {
    id: "MENU",
    label: "MENU",
    shiftLabel: "SETUP",
    colorType: "utility",
    action: { type: "OPEN_MENU" },
    shiftAction: { type: "OPEN_SETUP" },
    ariaLabel: "Menu and Setup",
  },
  {
    id: "ON",
    label: "ON",
    colorType: "utility",
    action: { type: "CLEAR" },
    ariaLabel: "Power on and clear",
  },

  // --- Function Row 1 ---
  {
    id: "OPTN",
    label: "OPTN",
    colorType: "function",
    action: { type: "OPEN_OPTN" },
    ariaLabel: "Options",
  },
  {
    id: "CALC",
    label: "CALC",
    shiftLabel: "SOLVE",
    alphaLabel: "=",
    colorType: "function",
    action: { type: "CALC" },
    shiftAction: { type: "SOLVE" },
    alphaAction: { type: "INSERT_TEXT", text: "=" },
    ariaLabel: "Calculate, solve equation, or equals",
  },
  {
    id: "integral",
    label: "∫dx",
    shiftLabel: "d/dx",
    alphaLabel: ":",
    colorType: "function",
    action: { type: "INSERT_TEMPLATE", template: "\\int_{#?}^{#?}{#?}\\,dx" },
    shiftAction: { type: "INSERT_TEMPLATE", template: "\\frac{d}{dx}\\left(#?\\right)" },
    alphaAction: { type: "INSERT_TEXT", text: ":" },
    ariaLabel: "Integral, derivative, or multi-statement colon",
  },
  {
    id: "fraction",
    label: "a/b",
    shiftLabel: "d/c",
    colorType: "function",
    action: { type: "INSERT_TEMPLATE", template: "\\frac{#?}{#?}" },
    shiftAction: { type: "INSERT_TEMPLATE", template: "#?\\frac{#?}{#?}" },
    ariaLabel: "Fraction or mixed fraction",
  },
  {
    id: "root",
    label: "√□",
    shiftLabel: "³√□",
    colorType: "function",
    action: { type: "INSERT_TEMPLATE", template: "\\sqrt{#?}" },
    shiftAction: { type: "INSERT_TEMPLATE", template: "\\sqrt[3]{#?}" },
    ariaLabel: "Square root or cubic root",
  },
  {
    id: "power_2",
    label: "x²",
    shiftLabel: "x³",
    baseNLabel: "DEC",
    colorType: "function",
    action: { type: "INSERT_TEXT", text: "^2" },
    shiftAction: { type: "INSERT_TEXT", text: "^3" },
    baseNAction: { type: "SET_BASE_N_MODE", mode: "DEC" },
    ariaLabel: "Square, cube, or Decimal base",
  },

  // --- Function Row 2 ---
  {
    id: "power_y",
    label: "xʸ",
    shiftLabel: "ⁿ√□",
    baseNLabel: "HEX",
    colorType: "function",
    action: { type: "INSERT_TEMPLATE", template: "^{#?}" },
    shiftAction: { type: "INSERT_TEMPLATE", template: "\\sqrt[#?]{#?}" },
    baseNAction: { type: "SET_BASE_N_MODE", mode: "HEX" },
    ariaLabel: "Power, nth root, or Hexadecimal base",
  },
  {
    id: "log",
    label: "log_□",
    shiftLabel: "10ˣ",
    baseNLabel: "BIN",
    colorType: "function",
    action: { type: "INSERT_TEMPLATE", template: "\\log_{#?}\\left(#?\\right)" },
    shiftAction: { type: "INSERT_TEMPLATE", template: "10^{#?}" },
    baseNAction: { type: "SET_BASE_N_MODE", mode: "BIN" },
    ariaLabel: "Logarithm with base, 10^x, or Binary base",
  },
  {
    id: "ln",
    label: "ln",
    shiftLabel: "eˣ",
    baseNLabel: "OCT",
    colorType: "function",
    action: { type: "INSERT_TEMPLATE", template: "\\ln\\left(#?\\right)" },
    shiftAction: { type: "INSERT_TEMPLATE", template: "e^{#?}" },
    baseNAction: { type: "SET_BASE_N_MODE", mode: "OCT" },
    ariaLabel: "Natural logarithm, e^x, or Octal base",
  },
  {
    id: "neg",
    label: "(-)",
    shiftLabel: "∠",
    alphaLabel: "A",
    complexLabel: "∠",
    colorType: "function",
    action: { type: "INSERT_TEXT", text: "-" },
    shiftAction: { type: "INSERT_TEXT", text: "\\angle" },
    alphaAction: { type: "VARIABLE", name: "A" },
    complexAction: { type: "INSERT_TEXT", text: "\\angle" },
    ariaLabel: "Negative sign, angle, or variable A",
  },
  {
    id: "dms",
    label: "° ' \"",
    shiftLabel: "←",
    alphaLabel: "B",
    colorType: "function",
    action: { type: "INSERT_TEXT", text: "^\\circ" },
    alphaAction: { type: "VARIABLE", name: "B" },
    ariaLabel: "Degree, minute, second, or variable B",
  },
  {
    id: "recip",
    label: "x⁻¹",
    shiftLabel: "x!",
    alphaLabel: "C",
    colorType: "function",
    action: { type: "INSERT_TEXT", text: "^{-1}" },
    shiftAction: { type: "INSERT_TEXT", text: "!" },
    alphaAction: { type: "VARIABLE", name: "C" },
    ariaLabel: "Reciprocal, factorial, or variable C",
  },

  // --- Function Row 3 ---
  {
    id: "sin",
    label: "sin",
    shiftLabel: "sin⁻¹",
    alphaLabel: "D",
    colorType: "function",
    action: { type: "INSERT_TEMPLATE", template: "\\sin\\left(#?\\right)" },
    shiftAction: { type: "INSERT_TEMPLATE", template: "\\arcsin\\left(#?\\right)" },
    alphaAction: { type: "VARIABLE", name: "D" },
    ariaLabel: "Sine, inverse sine, or variable D",
  },
  {
    id: "cos",
    label: "cos",
    shiftLabel: "cos⁻¹",
    alphaLabel: "E",
    colorType: "function",
    action: { type: "INSERT_TEMPLATE", template: "\\cos\\left(#?\\right)" },
    shiftAction: { type: "INSERT_TEMPLATE", template: "\\arccos\\left(#?\\right)" },
    alphaAction: { type: "VARIABLE", name: "E" },
    ariaLabel: "Cosine, inverse cosine, or variable E",
  },
  {
    id: "tan",
    label: "tan",
    shiftLabel: "tan⁻¹",
    alphaLabel: "F",
    colorType: "function",
    action: { type: "INSERT_TEMPLATE", template: "\\tan\\left(#?\\right)" },
    shiftAction: { type: "INSERT_TEMPLATE", template: "\\arctan\\left(#?\\right)" },
    alphaAction: { type: "VARIABLE", name: "F" },
    ariaLabel: "Tangent, inverse tangent, or variable F",
  },
  {
    id: "sto",
    label: "STO",
    shiftLabel: "RECALL",
    colorType: "function",
    action: { type: "STO" },
    shiftAction: { type: "RCL" },
    ariaLabel: "Store or recall memory",
  },
  {
    id: "eng",
    label: "ENG",
    shiftLabel: "←",
    complexLabel: "i",
    colorType: "function",
    action: { type: "ENG" },
    complexAction: { type: "INSERT_TEXT", text: "i" },
    ariaLabel: "Engineering notation or imaginary unit i",
  },
  {
    id: "bracket_open",
    label: "(",
    shiftLabel: "%",
    alphaLabel: "x",
    colorType: "function",
    action: { type: "INSERT_TEXT", text: "(" },
    shiftAction: { type: "INSERT_TEXT", text: "\\%" },
    alphaAction: { type: "VARIABLE", name: "x" },
    ariaLabel: "Left bracket, percent, or variable x",
  },

  // --- Function Row 4 ---
  {
    id: "bracket_close",
    label: ")",
    shiftLabel: ",",
    alphaLabel: "y",
    colorType: "function",
    action: { type: "INSERT_TEXT", text: ")" },
    shiftAction: { type: "INSERT_TEXT", text: "," },
    alphaAction: { type: "VARIABLE", name: "y" },
    ariaLabel: "Right bracket, comma, or variable y",
  },
  {
    id: "sd",
    label: "S⇔D",
    shiftLabel: "a b/c ⇔ d/c",
    alphaLabel: "z",
    colorType: "function",
    action: { type: "TOGGLE_SD" },
    alphaAction: { type: "VARIABLE", name: "z" },
    ariaLabel: "Surd to decimal conversion or variable z",
  },
  {
    id: "m_plus",
    label: "M+",
    shiftLabel: "M-",
    alphaLabel: "M",
    colorType: "function",
    action: { type: "M_PLUS" },
    shiftAction: { type: "M_MINUS" },
    alphaAction: { type: "VARIABLE", name: "M" },
    ariaLabel: "Memory plus, minus, or variable M",
  },

  // --- Numeric & Operations Pad ---
  {
    id: "7",
    label: "7",
    colorType: "digit",
    action: { type: "DIGIT", value: "7" },
    ariaLabel: "Digit 7",
  },
  {
    id: "8",
    label: "8",
    colorType: "digit",
    action: { type: "DIGIT", value: "8" },
    ariaLabel: "Digit 8",
  },
  {
    id: "9",
    label: "9",
    colorType: "digit",
    action: { type: "DIGIT", value: "9" },
    ariaLabel: "Digit 9",
  },
  {
    id: "DEL",
    label: "DEL",
    shiftLabel: "INS",
    colorType: "action",
    action: { type: "DELETE" },
    shiftAction: { type: "UNDO" },
    ariaLabel: "Delete or Undo",
  },
  {
    id: "AC",
    label: "AC",
    shiftLabel: "RESET",
    colorType: "action",
    action: { type: "CLEAR" },
    ariaLabel: "All clear",
  },

  {
    id: "4",
    label: "4",
    colorType: "digit",
    action: { type: "DIGIT", value: "4" },
    ariaLabel: "Digit 4",
  },
  {
    id: "5",
    label: "5",
    colorType: "digit",
    action: { type: "DIGIT", value: "5" },
    ariaLabel: "Digit 5",
  },
  {
    id: "6",
    label: "6",
    colorType: "digit",
    action: { type: "DIGIT", value: "6" },
    ariaLabel: "Digit 6",
  },
  {
    id: "times",
    label: "×",
    shiftLabel: "nPr",
    colorType: "digit",
    action: { type: "OPERATOR", op: "\\times" },
    shiftAction: { type: "INSERT_TEXT", text: " \\text{nPr} " },
    ariaLabel: "Multiply or permutation",
  },
  {
    id: "divide",
    label: "÷",
    shiftLabel: "nCr",
    colorType: "digit",
    action: { type: "OPERATOR", op: "\\div" },
    shiftAction: { type: "INSERT_TEXT", text: " \\text{nCr} " },
    ariaLabel: "Divide or combination",
  },

  {
    id: "1",
    label: "1",
    colorType: "digit",
    action: { type: "DIGIT", value: "1" },
    ariaLabel: "Digit 1",
  },
  {
    id: "2",
    label: "2",
    colorType: "digit",
    action: { type: "DIGIT", value: "2" },
    ariaLabel: "Digit 2",
  },
  {
    id: "3",
    label: "3",
    colorType: "digit",
    action: { type: "DIGIT", value: "3" },
    ariaLabel: "Digit 3",
  },
  {
    id: "plus",
    label: "+",
    shiftLabel: "Pol",
    colorType: "digit",
    action: { type: "OPERATOR", op: "+" },
    ariaLabel: "Add or polar coordinates",
  },
  {
    id: "minus",
    label: "−",
    shiftLabel: "Rec",
    colorType: "digit",
    action: { type: "OPERATOR", op: "-" },
    ariaLabel: "Subtract or rectangular coordinates",
  },

  {
    id: "0",
    label: "0",
    colorType: "digit",
    action: { type: "DIGIT", value: "0" },
    ariaLabel: "Digit 0",
  },
  {
    id: "dot",
    label: ".",
    shiftLabel: "Ran#",
    colorType: "digit",
    action: { type: "DIGIT", value: "." },
    shiftAction: { type: "INSERT_TEXT", text: "Ran#" },
    ariaLabel: "Decimal point or random number",
  },
  {
    id: "exp",
    label: "×10ˣ",
    shiftLabel: "π",
    alphaLabel: "e",
    colorType: "digit",
    action: { type: "INSERT_TEMPLATE", template: "\\cdot 10^{#?}" },
    shiftAction: { type: "INSERT_TEXT", text: "\\pi" },
    alphaAction: { type: "INSERT_TEXT", text: "e" },
    ariaLabel: "Power of 10, pi, or e",
  },
  {
    id: "Ans",
    label: "Ans",
    shiftLabel: "PreAns",
    colorType: "digit",
    action: { type: "INSERT_TEXT", text: "Ans" },
    shiftAction: { type: "INSERT_TEXT", text: "PreAns" },
    ariaLabel: "Last answer or previous answer",
  },
  {
    id: "EXE",
    label: "=",
    colorType: "digit",
    action: { type: "EXECUTE" },
    ariaLabel: "Execute calculation",
  },
];

export function resolveKeyAction(
  key: CalculatorKey,
  isShift: boolean,
  isAlpha: boolean,
  currentMode?: string
): SemanticAction {
  if (isShift && key.shiftAction) {
    return key.shiftAction;
  }
  if (isAlpha && key.alphaAction) {
    return key.alphaAction;
  }
  if (currentMode === "COMPLEX" && key.complexAction) {
    return key.complexAction;
  }
  if (currentMode === "BASE_N" && key.baseNAction) {
    return key.baseNAction;
  }
  return key.action;
}
