/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 * Grade 12 Curriculum Taxonomy & Assessment Metadata Catalog
 * Conforms to:
 * 1. Chương trình Giáo dục phổ thông 2018 (Thông tư 32/2018/TT-BGDĐT)
 * 2. Cấu trúc định dạng đề thi Kỳ thi tốt nghiệp THPT từ năm 2025 (Quyết định 764/QĐ-BGDĐT)
 */

export interface CurriculumMetadata {
  curriculumName: string;
  officialSource: string;
  decisionNumber: string;
  effectiveYear: number;
  version: string;
  lastCheckedDate: string;
}

export const GRADE_12_CURRICULUM_METADATA: CurriculumMetadata = {
  curriculumName: "Chương trình Giáo dục phổ thông 2018 - Cấp THPT (Lớp 12)",
  officialSource: "Bộ Giáo dục và Đào tạo Việt Nam",
  decisionNumber: "Thông tư 32/2018/TT-BGDĐT & Quyết định số 764/QĐ-BGDĐT ngày 08/03/2024",
  effectiveYear: 2025,
  version: "GDPT_2018_THPT_2025_V1",
  lastCheckedDate: "2026-10-10",
};

export type Grade12Subject = "math" | "physics" | "chemistry" | "computer_science";

export type CognitiveLevel = "remember" | "understand" | "apply" | "analyze";

export interface TaxonomySkill {
  id: string;
  name: string;
  description: string;
  cognitiveLevel: CognitiveLevel;
}

export interface TaxonomyTopic {
  id: string;
  code: string;
  title: string;
  chapterId: string;
  chapterTitle: string;
  subject: Grade12Subject;
  grade: 12;
  description: string;
  skills: TaxonomySkill[];
  cognitiveLevels: CognitiveLevel[];
  supportedFormats: Array<"choice" | "true_false_group" | "numeric" | "matching" | "code_trace">;
  prerequisites: string[];
  recommendedOrder: number;
  tags: string[];
}

export interface TaxonomyChapter {
  id: string;
  number: number;
  title: string;
  subject: Grade12Subject;
  description: string;
  topicIds: string[];
}

export interface SubjectTaxonomy {
  subject: Grade12Subject;
  nameVi: string;
  icon: string;
  accentColor: string;
  examDurationMinutes: number;
  examQuestionCount: {
    total: number;
    part1_multipleChoice: number;
    part2_trueFalseGroup: number;
    part3_shortAnswer: number;
  };
  chapters: TaxonomyChapter[];
  topics: TaxonomyTopic[];
}

// ============================================================================
// 1. TOÁN HỌC 12 (MATHEMATICS)
// ============================================================================
export const MATH_TAXONOMY: SubjectTaxonomy = {
  subject: "math",
  nameVi: "Toán học 12",
  icon: "Calculator",
  accentColor: "blue",
  examDurationMinutes: 90,
  examQuestionCount: {
    total: 22,
    part1_multipleChoice: 12,
    part2_trueFalseGroup: 4,
    part3_shortAnswer: 6,
  },
  chapters: [
    {
      id: "math_ch1",
      number: 1,
      title: "Ứng dụng đạo hàm để khảo sát và vẽ đồ thị hàm số",
      subject: "math",
      description: "Tính đơn điệu, cực trị, GTLN-GTNN, đường tiệm cận, khảo sát hàm số và bài toán tối ưu thực tế.",
      topicIds: ["math_t1_monotonicity", "math_t2_extremum", "math_t3_minmax", "math_t4_asymptote", "math_t5_graph_optimize"],
    },
    {
      id: "math_ch2",
      number: 2,
      title: "Vectơ và hệ tọa độ trong không gian",
      subject: "math",
      description: "Vectơ trong không gian, hệ tọa độ Oxyz và các phép toán vectơ không gian.",
      topicIds: ["math_t6_vector_space", "math_t7_oxyz_coords"],
    },
    {
      id: "math_ch3",
      number: 3,
      title: "Các số đặc trưng đo mức độ phân tán của mẫu số liệu ghép nhóm",
      subject: "math",
      description: "Khoảng biến thiên, khoảng tứ phân vị, phương sai và độ lệch chuẩn của số liệu thống kê.",
      topicIds: ["math_t8_grouped_dispersion"],
    },
    {
      id: "math_ch4",
      number: 4,
      title: "Nguyên hàm và Tích phân",
      subject: "math",
      description: "Khái niệm nguyên hàm, bảng nguyên hàm cơ bản, phương pháp tích phân, ứng dụng tính diện tích và thể tích.",
      topicIds: ["math_t9_antiderivative", "math_t10_integral_apps"],
    },
    {
      id: "math_ch5",
      number: 5,
      title: "Phương pháp tọa độ trong không gian (Oxyz nâng cao)",
      subject: "math",
      description: "Phương trình mặt phẳng, phương trình đường thẳng, phương trình mặt cầu và vị trí tương đối.",
      topicIds: ["math_t11_plane_sphere", "math_t12_line_relative_pos"],
    },
    {
      id: "math_ch6",
      number: 6,
      title: "Xác suất có điều kiện",
      subject: "math",
      description: "Định nghĩa xác suất có điều kiện, công thức nhân xác suất, công thức xác suất toàn phần và công thức Bayes.",
      topicIds: ["math_t13_conditional_prob", "math_t14_bayes_formula"],
    },
  ],
  topics: [
    {
      id: "math_t1_monotonicity",
      code: "TOAN12.1.1",
      title: "Tính đơn điệu của hàm số",
      chapterId: "math_ch1",
      chapterTitle: "Ứng dụng đạo hàm khảo sát hàm số",
      subject: "math",
      grade: 12,
      description: "Xét dấu đạo hàm f'(x), tìm các khoảng đồng biến, nghịch biến của hàm bậc ba, phân thức và hàm số chứa tham số.",
      skills: [
        { id: "sk_m1", name: "Xét tính đơn điệu từ bảng biến thiên và đồ thị", description: "Nhận biết khoảng đơn điệu", cognitiveLevel: "remember" },
        { id: "sk_m2", name: "Tìm khoảng đơn điệu qua đạo hàm f'(x)", description: "Tính và xét dấu đạo hàm", cognitiveLevel: "understand" },
        { id: "sk_m3", name: "Đơn điệu có chứa tham số m", description: "Biện luận tham số m", cognitiveLevel: "apply" },
      ],
      cognitiveLevels: ["remember", "understand", "apply", "analyze"],
      supportedFormats: ["choice", "true_false_group", "numeric"],
      prerequisites: [],
      recommendedOrder: 1,
      tags: ["Đạo hàm", "Đơn điệu", "Khảo sát hàm số"],
    },
    {
      id: "math_t2_extremum",
      code: "TOAN12.1.2",
      title: "Cực trị của hàm số",
      chapterId: "math_ch1",
      chapterTitle: "Ứng dụng đạo hàm khảo sát hàm số",
      subject: "math",
      grade: 12,
      description: "Quy tắc tìm điểm cực trị, giá trị cực trị, điều kiện để hàm số có cực trị và tương giao đường thẳng đi qua các điểm cực trị.",
      skills: [
        { id: "sk_m4", name: "Xác định điểm cực đại, cực tiểu", description: "Đọc điểm cực trị từ bảng biến thiên", cognitiveLevel: "remember" },
        { id: "sk_m5", name: "Áp dụng định lý đạo hàm cấp hai", description: "Sử dụng f''(x) tìm cực trị", cognitiveLevel: "understand" },
        { id: "sk_m6", name: "Cực trị hàm bậc 3 chứa tham số m", description: "Điều kiện có 2 điểm cực trị", cognitiveLevel: "apply" },
      ],
      cognitiveLevels: ["remember", "understand", "apply", "analyze"],
      supportedFormats: ["choice", "true_false_group", "numeric"],
      prerequisites: ["math_t1_monotonicity"],
      recommendedOrder: 2,
      tags: ["Cực trị", "Cực đại", "Cực tiểu"],
    },
    {
      id: "math_t3_minmax",
      code: "TOAN12.1.3",
      title: "Giá trị lớn nhất và nhỏ nhất của hàm số",
      chapterId: "math_ch1",
      chapterTitle: "Ứng dụng đạo hàm khảo sát hàm số",
      subject: "math",
      grade: 12,
      description: "Quy tắc tìm GTLN - GTNN trên đoạn [a; b], trên khoảng và ứng dụng bất đẳng thức.",
      skills: [
        { id: "sk_m7", name: "Tìm Max - Min trên đoạn đóng", description: "So sánh giá trị tại các điểm tới hạn và mút đoạn", cognitiveLevel: "remember" },
        { id: "sk_m8", name: "Tìm Max - Min trên khoảng bằng bảng biến thiên", description: "Khảo sát giới hạn tại vô cực", cognitiveLevel: "understand" },
        { id: "sk_m9", name: "Ứng dụng Max - Min giải bài toán thực tế", description: "Mô hình hóa chi phí, diện tích, thể tích", cognitiveLevel: "apply" },
      ],
      cognitiveLevels: ["remember", "understand", "apply", "analyze"],
      supportedFormats: ["choice", "true_false_group", "numeric"],
      prerequisites: ["math_t1_monotonicity"],
      recommendedOrder: 3,
      tags: ["GTLN", "GTNN", "Max Min"],
    },
    {
      id: "math_t4_asymptote",
      code: "TOAN12.1.4",
      title: "Đường tiệm cận của đồ thị hàm số",
      chapterId: "math_ch1",
      chapterTitle: "Ứng dụng đạo hàm khảo sát hàm số",
      subject: "math",
      grade: 12,
      description: "Đường tiệm cận đứng, tiệm cận ngang và tiệm cận xiên (nội dung mới chương trình 2018).",
      skills: [
        { id: "sk_m10", name: "Nhận biết tiệm cận đứng và tiệm cận ngang", description: "Giới hạn tại điểm gián đoạn và vô cực", cognitiveLevel: "remember" },
        { id: "sk_m11", name: "Xác định tiệm cận xiên hàm phân thức bậc 2/1", description: "Chia đa thức tìm đường tiệm cận xiên y = ax + b", cognitiveLevel: "understand" },
      ],
      cognitiveLevels: ["remember", "understand", "apply"],
      supportedFormats: ["choice", "true_false_group", "numeric"],
      prerequisites: [],
      recommendedOrder: 4,
      tags: ["Tiệm cận đứng", "Tiệm cận ngang", "Tiệm cận xiên"],
    },
    {
      id: "math_t5_graph_optimize",
      code: "TOAN12.1.5",
      title: "Khảo sát hàm số & Bài toán tối ưu thực tế",
      chapterId: "math_ch1",
      chapterTitle: "Ứng dụng đạo hàm khảo sát hàm số",
      subject: "math",
      grade: 12,
      description: "Nhận dạng đồ thị, tâm đối xứng, tương giao đồ thị và bài toán tối ưu thực tiễn (kinh tế, kỹ thuật).",
      skills: [
        { id: "sk_m12", name: "Nhận dạng đồ thị và xác định dấu hệ số", description: "Xác định a, b, c, d từ hình dáng đồ thị", cognitiveLevel: "understand" },
        { id: "sk_m13", name: "Giải bài toán tối ưu hóa cắt tôn, làm hộp, lợi nhuận", description: "Mô hình hàm mục tiêu và giải đạo hàm", cognitiveLevel: "apply" },
      ],
      cognitiveLevels: ["remember", "understand", "apply", "analyze"],
      supportedFormats: ["choice", "true_false_group", "numeric"],
      prerequisites: ["math_t3_minmax"],
      recommendedOrder: 5,
      tags: ["Tối ưu thực tế", "Khảo sát đồ thị", "Tâm đối xứng"],
    },
    {
      id: "math_t6_vector_space",
      code: "TOAN12.2.1",
      title: "Vectơ trong không gian",
      chapterId: "math_ch2",
      chapterTitle: "Vectơ và hệ tọa độ trong không gian",
      subject: "math",
      grade: 12,
      description: "Quy tắc 3 điểm, hình bình hành, hình hộp, tích vô hướng của 2 vectơ trong không gian.",
      skills: [
        { id: "sk_m14", name: "Cộng trừ vectơ và quy tắc hình hộp", description: "Phép toán vectơ không gian", cognitiveLevel: "remember" },
        { id: "sk_m15", name: "Tính góc và tích vô hướng 2 vectơ", description: "Góc giữa 2 đường thẳng", cognitiveLevel: "understand" },
      ],
      cognitiveLevels: ["remember", "understand", "apply"],
      supportedFormats: ["choice", "true_false_group", "numeric"],
      prerequisites: [],
      recommendedOrder: 6,
      tags: ["Vectơ", "Tích vô hướng", "Góc"],
    },
    {
      id: "math_t7_oxyz_coords",
      code: "TOAN12.2.2",
      title: "Hệ tọa độ Oxyz trong không gian",
      chapterId: "math_ch2",
      chapterTitle: "Vectơ và hệ tọa độ trong không gian",
      subject: "math",
      grade: 12,
      description: "Tọa độ điểm, tọa độ vectơ, độ dài vectơ, khoảng cách giữa hai điểm trong Oxyz.",
      skills: [
        { id: "sk_m16", name: "Xác định tọa độ điểm và vectơ", description: "Công thức tọa độ Oxyz", cognitiveLevel: "remember" },
        { id: "sk_m17", name: "Tính độ dài đoạn thẳng và tích có hướng", description: "Ứng dụng tọa độ tính diện tích tam giác", cognitiveLevel: "understand" },
      ],
      cognitiveLevels: ["remember", "understand", "apply"],
      supportedFormats: ["choice", "true_false_group", "numeric"],
      prerequisites: ["math_t6_vector_space"],
      recommendedOrder: 7,
      tags: ["Oxyz", "Tọa độ điểm", "Độ dài"],
    },
    {
      id: "math_t8_grouped_dispersion",
      code: "TOAN12.3.1",
      title: "Đo mức độ phân tán mẫu số liệu ghép nhóm",
      chapterId: "math_ch3",
      chapterTitle: "Các số đặc trưng đo mức độ phân tán",
      subject: "math",
      grade: 12,
      description: "Khoảng biến thiên, khoảng tứ phân vị, phương sai và độ lệch chuẩn của số liệu thống kê ghép nhóm.",
      skills: [
        { id: "sk_m18", name: "Tính khoảng biến thiên và khoảng tứ phân vị", description: "Đọc nhóm chứa tứ phân vị", cognitiveLevel: "understand" },
        { id: "sk_m19", name: "Tính phương sai và độ lệch chuẩn", description: "Đánh giá mức độ đồng đều của dữ liệu", cognitiveLevel: "apply" },
      ],
      cognitiveLevels: ["remember", "understand", "apply"],
      supportedFormats: ["choice", "true_false_group", "numeric"],
      prerequisites: [],
      recommendedOrder: 8,
      tags: ["Thống kê", "Mẫu ghép nhóm", "Độ lệch chuẩn", "Phương sai"],
    },
    {
      id: "math_t9_antiderivative",
      code: "TOAN12.4.1",
      title: "Nguyên hàm cơ bản & Tích phân",
      chapterId: "math_ch4",
      chapterTitle: "Nguyên hàm và Tích phân",
      subject: "math",
      grade: 12,
      description: "Bảng nguyên hàm cơ bản, tích phân xác định và phương pháp đổi biến số, từng phần.",
      skills: [
        { id: "sk_m20", name: "Tính nguyên hàm các hàm số cơ bản", description: "Lũy thừa, lượng giác, mũ", cognitiveLevel: "remember" },
        { id: "sk_m21", name: "Tính tích phân theo công thức Newton-Leibniz", description: "Đổi biến số và từng phần", cognitiveLevel: "understand" },
      ],
      cognitiveLevels: ["remember", "understand", "apply", "analyze"],
      supportedFormats: ["choice", "true_false_group", "numeric"],
      prerequisites: ["math_t1_monotonicity"],
      recommendedOrder: 9,
      tags: ["Nguyên hàm", "Tích phân", "Đổi biến"],
    },
    {
      id: "math_t10_integral_apps",
      code: "TOAN12.4.2",
      title: "Ứng dụng hình học của tích phân",
      chapterId: "math_ch4",
      chapterTitle: "Nguyên hàm và Tích phân",
      subject: "math",
      grade: 12,
      description: "Tính diện tích hình phẳng giới hạn bởi các đường cong và tính thể tích vật thể tròn xoay.",
      skills: [
        { id: "sk_m22", name: "Tính diện tích hình phẳng", description: "Tích phân giá trị tuyệt đối |f(x) - g(x)|", cognitiveLevel: "apply" },
        { id: "sk_m23", name: "Tính thể tích khối tròn xoay", description: "Công thức V = pi * int(f^2)", cognitiveLevel: "apply" },
      ],
      cognitiveLevels: ["understand", "apply", "analyze"],
      supportedFormats: ["choice", "true_false_group", "numeric"],
      prerequisites: ["math_t9_antiderivative"],
      recommendedOrder: 10,
      tags: ["Diện tích hình phẳng", "Thể tích tròn xoay"],
    },
    {
      id: "math_t11_plane_sphere",
      code: "TOAN12.5.1",
      title: "Phương trình mặt phẳng và mặt cầu Oxyz",
      chapterId: "math_ch5",
      chapterTitle: "Phương pháp tọa độ trong không gian",
      subject: "math",
      grade: 12,
      description: "Vectơ pháp tuyến, phương trình tổng quát mặt phẳng, tâm và bán kính mặt cầu, vị trí tương đối.",
      skills: [
        { id: "sk_m24", name: "Viết phương trình mặt phẳng qua 1 điểm và VTPT", description: "Công thức A(x-x0)+B(y-y0)+C(z-z0)=0", cognitiveLevel: "remember" },
        { id: "sk_m25", name: "Viết phương trình mặt cầu và tính khoảng cách", description: "Khoảng cách từ điểm đến mặt phẳng", cognitiveLevel: "understand" },
      ],
      cognitiveLevels: ["remember", "understand", "apply"],
      supportedFormats: ["choice", "true_false_group", "numeric"],
      prerequisites: ["math_t7_oxyz_coords"],
      recommendedOrder: 11,
      tags: ["Mặt phẳng", "Mặt cầu", "Khoảng cách"],
    },
    {
      id: "math_t12_line_relative_pos",
      code: "TOAN12.5.2",
      title: "Phương trình đường thẳng trong không gian",
      chapterId: "math_ch5",
      chapterTitle: "Phương pháp tọa độ trong không gian",
      subject: "math",
      grade: 12,
      description: "Vectơ chỉ phương, phương trình tham số, chính tắc của đường thẳng, góc và khoảng cách.",
      skills: [
        { id: "sk_m26", name: "Lập phương trình tham số đường thẳng", description: "Vectơ chỉ phương và điểm đi qua", cognitiveLevel: "remember" },
        { id: "sk_m27", name: "Xét vị trí tương đối giữa đường thẳng và mặt phẳng", description: "Song song, vuông góc, cắt nhau", cognitiveLevel: "apply" },
      ],
      cognitiveLevels: ["remember", "understand", "apply"],
      supportedFormats: ["choice", "true_false_group", "numeric"],
      prerequisites: ["math_t11_plane_sphere"],
      recommendedOrder: 12,
      tags: ["Đường thẳng", "Vị trí tương đối", "Góc"],
    },
    {
      id: "math_t13_conditional_prob",
      code: "TOAN12.6.1",
      title: "Xác suất có điều kiện và Công thức nhân",
      chapterId: "math_ch6",
      chapterTitle: "Xác suất có điều kiện",
      subject: "math",
      grade: 12,
      description: "Định nghĩa xác suất có điều kiện P(A|B) = P(AB)/P(B), công thức nhân xác suất và biến cố độc lập.",
      skills: [
        { id: "sk_m28", name: "Tính xác suất có điều kiện từ bảng dữ liệu", description: "Tính P(A|B)", cognitiveLevel: "understand" },
        { id: "sk_m29", name: "Áp dụng công thức nhân xác suất", description: "Bài toán thực tế rút thăm, bắn bia", cognitiveLevel: "apply" },
      ],
      cognitiveLevels: ["remember", "understand", "apply"],
      supportedFormats: ["choice", "true_false_group", "numeric"],
      prerequisites: [],
      recommendedOrder: 13,
      tags: ["Xác suất có điều kiện", "Công thức nhân"],
    },
    {
      id: "math_t14_bayes_formula",
      code: "TOAN12.6.2",
      title: "Công thức xác suất toàn phần và Công thức Bayes",
      chapterId: "math_ch6",
      chapterTitle: "Xác suất có điều kiện",
      subject: "math",
      grade: 12,
      description: "Mô hình nhóm biến cố đầy đủ, công thức xác suất toàn phần và công thức Bayes trong chẩn đoán y tế, kiểm tra chất lượng.",
      skills: [
        { id: "sk_m30", name: "Xây dựng hệ biến cố đầy đủ", description: "Phân chia không gian mẫu", cognitiveLevel: "understand" },
        { id: "sk_m31", name: "Tính xác suất tiên nghiệm và hậu nghiệm qua công thức Bayes", description: "Chẩn đoán bệnh lý", cognitiveLevel: "apply" },
      ],
      cognitiveLevels: ["understand", "apply", "analyze"],
      supportedFormats: ["choice", "true_false_group", "numeric"],
      prerequisites: ["math_t13_conditional_prob"],
      recommendedOrder: 14,
      tags: ["Xác suất toàn phần", "Công thức Bayes"],
    },
  ],
};

// ============================================================================
// 2. VẬT LÝ 12 (PHYSICS)
// ============================================================================
export const PHYSICS_TAXONOMY: SubjectTaxonomy = {
  subject: "physics",
  nameVi: "Vật lý 12",
  icon: "Atom",
  accentColor: "rose",
  examDurationMinutes: 50,
  examQuestionCount: {
    total: 28,
    part1_multipleChoice: 18,
    part2_trueFalseGroup: 4,
    part3_shortAnswer: 6,
  },
  chapters: [
    {
      id: "phys_ch1",
      number: 1,
      title: "Vật lí nhiệt",
      subject: "physics",
      description: "Cấu trúc chất, thang nhiệt độ, nội năng, định luật 1 nhiệt động lực học, nhiệt dung riêng, nhiệt nóng chảy và hóa hơi.",
      topicIds: ["phys_t1_matter_temp", "phys_t2_first_law", "phys_t3_heat_capacity", "phys_t4_phase_change"],
    },
    {
      id: "phys_ch2",
      number: 2,
      title: "Khí lí tưởng",
      subject: "physics",
      description: "Mô hình động học phân tử, định luật Boyle, định luật Charles, phương trình trạng thái Clapeyron - Mendeleev.",
      topicIds: ["phys_t5_ideal_gas_laws", "phys_t6_kinetic_theory"],
    },
    {
      id: "phys_ch3",
      number: 3,
      title: "Từ trường",
      subject: "physics",
      description: "Tương tác từ, cảm ứng từ, lực từ, từ thông, hiện tượng cảm ứng điện từ và sóng điện từ.",
      topicIds: ["phys_t7_magnetic_force", "phys_t8_induction_emf"],
    },
    {
      id: "phys_ch4",
      number: 4,
      title: "Vật lí hạt nhân",
      subject: "physics",
      description: "Cấu trúc hạt nhân, độ hụt khối, năng lượng liên kết, phân rã phóng xạ, phản ứng hạt nhân phân hạch và nhiệt hạch.",
      topicIds: ["phys_t9_nuclear_binding", "phys_t10_radioactivity"],
    },
  ],
  topics: [
    {
      id: "phys_t1_matter_temp",
      code: "LY12.1.1",
      title: "Cấu trúc chất & Thang nhiệt độ",
      chapterId: "phys_ch1",
      chapterTitle: "Vật lí nhiệt",
      subject: "physics",
      grade: 12,
      description: "Mô hình động học phân tử, thể rắn, lỏng, khí, thang nhiệt độ Celsius và Kelvin (T(K) = t(°C) + 273.15).",
      skills: [
        { id: "sk_p1", name: "Chuyển đổi nhiệt độ giữa thang Celsius và Kelvin", description: "T(K) = t(C) + 273.15", cognitiveLevel: "remember" },
        { id: "sk_p2", name: "Giải thích chuyển động phân tử và nhiệt độ", description: "Bản chất vi mô của nhiệt độ", cognitiveLevel: "understand" },
      ],
      cognitiveLevels: ["remember", "understand"],
      supportedFormats: ["choice", "true_false_group", "numeric"],
      prerequisites: [],
      recommendedOrder: 1,
      tags: ["Kelvin", "Celsius", "Cấu tạo chất"],
    },
    {
      id: "phys_t2_first_law",
      code: "LY12.1.2",
      title: "Nội năng & Định luật I Nhiệt động lực học",
      chapterId: "phys_ch1",
      chapterTitle: "Vật lí nhiệt",
      subject: "physics",
      grade: 12,
      description: "Độ biến thiên nội năng Delta U = A + Q, quy ước dấu công và nhiệt lượng, động cơ nhiệt và hiệu suất.",
      skills: [
        { id: "sk_p3", name: "Áp dụng định luật 1 tính Delta U, A, Q", description: "Quy ước dấu hệ nhận/truyền công và nhiệt", cognitiveLevel: "understand" },
        { id: "sk_p4", name: "Tính hiệu suất động cơ nhiệt", description: "H = A / Q1", cognitiveLevel: "apply" },
      ],
      cognitiveLevels: ["remember", "understand", "apply"],
      supportedFormats: ["choice", "true_false_group", "numeric"],
      prerequisites: ["phys_t1_matter_temp"],
      recommendedOrder: 2,
      tags: ["Nội năng", "Định luật 1 NĐLH", "Quy ước dấu"],
    },
    {
      id: "phys_t3_heat_capacity",
      code: "LY12.1.3",
      title: "Nhiệt dung riêng & Cân bằng nhiệt",
      chapterId: "phys_ch1",
      chapterTitle: "Vật lí nhiệt",
      subject: "physics",
      grade: 12,
      description: "Công thức Q = mc Delta T, phương trình cân bằng nhiệt và bài toán hao phí nhiệt ra môi trường.",
      skills: [
        { id: "sk_p5", name: "Tính nhiệt lượng làm thay đổi nhiệt độ", description: "Q = mc(t2 - t1)", cognitiveLevel: "remember" },
        { id: "sk_p6", name: "Giải phương trình cân bằng nhiệt nhiều vật", description: "Sigma Q tỏa = Sigma Q thu", cognitiveLevel: "apply" },
      ],
      cognitiveLevels: ["remember", "understand", "apply"],
      supportedFormats: ["choice", "true_false_group", "numeric"],
      prerequisites: ["phys_t1_matter_temp"],
      recommendedOrder: 3,
      tags: ["Nhiệt dung riêng", "Cân bằng nhiệt"],
    },
    {
      id: "phys_t4_phase_change",
      code: "LY12.1.4",
      title: "Sự chuyển thể & Nhiệt nóng chảy, Nhiệt hóa hơi",
      chapterId: "phys_ch1",
      chapterTitle: "Vật lí nhiệt",
      subject: "physics",
      grade: 12,
      description: "Nhiệt nóng chảy riêng Q = m*lambda, nhiệt hóa hơi riêng Q = m*L và đồ thị nhiệt độ - thời gian.",
      skills: [
        { id: "sk_p7", name: "Tính nhiệt lượng nóng chảy và hóa hơi", description: "Q = m*lambda và Q = m*L", cognitiveLevel: "remember" },
        { id: "sk_p8", name: "Đọc đồ thị chuyển thể và tính nhiệt tổng cộng", description: "Đồ thị T theo t", cognitiveLevel: "apply" },
      ],
      cognitiveLevels: ["remember", "understand", "apply"],
      supportedFormats: ["choice", "true_false_group", "numeric"],
      prerequisites: ["phys_t3_heat_capacity"],
      recommendedOrder: 4,
      tags: ["Nhiệt nóng chảy", "Nhiệt hóa hơi", "Đồ thị chuyển thể"],
    },
    {
      id: "phys_t5_ideal_gas_laws",
      code: "LY12.2.1",
      title: "Các định luật chất khí & Phương trình Clapeyron - Mendeleev",
      chapterId: "phys_ch2",
      chapterTitle: "Khí lí tưởng",
      subject: "physics",
      grade: 12,
      description: "Định luật Boyle (đẳng nhiệt), Charles (đẳng tích), Gay-Lussac (đẳng áp) và pV = nRT.",
      skills: [
        { id: "sk_p9", name: "Áp dụng định luật Boyle và Charles", description: "p1V1 = p2V2; p1/T1 = p2/T2", cognitiveLevel: "remember" },
        { id: "sk_p10", name: "Phương trình trạng thái pV = (m/M)RT", description: "Tính áp suất, thể tích, nhiệt độ", cognitiveLevel: "apply" },
      ],
      cognitiveLevels: ["remember", "understand", "apply", "analyze"],
      supportedFormats: ["choice", "true_false_group", "numeric"],
      prerequisites: ["phys_t1_matter_temp"],
      recommendedOrder: 5,
      tags: ["Boyle", "Charles", "Clapeyron - Mendeleev", "Khí lý tưởng"],
    },
    {
      id: "phys_t6_kinetic_theory",
      code: "LY12.2.2",
      title: "Thuyết động học phân tử chất khí",
      chapterId: "phys_ch2",
      chapterTitle: "Khí lí tưởng",
      subject: "physics",
      grade: 12,
      description: "Động năng tịnh tiến trung bình Ed = 3/2 * kT, căn bậc hai của vận tốc bình phương trung bình v_rms = sqrt(3RT/M).",
      skills: [
        { id: "sk_p11", name: "Tính động năng tịnh tiến phân tử khí", description: "Ed = 3/2 * k * T", cognitiveLevel: "understand" },
        { id: "sk_p12", name: "Tính vận tốc căn quân phương v_rms", description: "v = sqrt(3RT/M)", cognitiveLevel: "apply" },
      ],
      cognitiveLevels: ["remember", "understand", "apply"],
      supportedFormats: ["choice", "true_false_group", "numeric"],
      prerequisites: ["phys_t5_ideal_gas_laws"],
      recommendedOrder: 6,
      tags: ["Động học phân tử", "Vận tốc căn quân phương"],
    },
    {
      id: "phys_t7_magnetic_force",
      code: "LY12.3.1",
      title: "Từ trường & Lực từ tác dụng lên dòng điện",
      chapterId: "phys_ch3",
      chapterTitle: "Từ trường",
      subject: "physics",
      grade: 12,
      description: "Cảm ứng từ B, lực từ Ampère F = B*I*L*sin(alpha), quy tắc bàn tay trái.",
      skills: [
        { id: "sk_p13", name: "Xác định chiều lực từ theo quy tắc bàn tay trái", description: "Quy tắc bàn tay trái", cognitiveLevel: "remember" },
        { id: "sk_p14", name: "Tính độ lớn lực từ tác dụng lên đoạn dây", description: "F = BIL sin(alpha)", cognitiveLevel: "apply" },
      ],
      cognitiveLevels: ["remember", "understand", "apply"],
      supportedFormats: ["choice", "true_false_group", "numeric"],
      prerequisites: [],
      recommendedOrder: 7,
      tags: ["Lực từ", "Cảm ứng từ", "Bàn tay trái"],
    },
    {
      id: "phys_t8_induction_emf",
      code: "LY12.3.2",
      title: "Hiện tượng cảm ứng điện từ & Từ thông",
      chapterId: "phys_ch3",
      chapterTitle: "Từ trường",
      subject: "physics",
      grade: 12,
      description: "Từ thông Phi = B*S*cos(alpha), định luật Faraday ec = -Delta Phi / Delta t, định luật Lenz.",
      skills: [
        { id: "sk_p15", name: "Xác định chiều dòng điện cảm ứng theo định luật Lenz", description: "Chống lại nguyên nhân sinh ra nó", cognitiveLevel: "understand" },
        { id: "sk_p16", name: "Tính suất điện động cảm ứng", description: "ec = -Delta Phi / Delta t", cognitiveLevel: "apply" },
      ],
      cognitiveLevels: ["remember", "understand", "apply"],
      supportedFormats: ["choice", "true_false_group", "numeric"],
      prerequisites: ["phys_t7_magnetic_force"],
      recommendedOrder: 8,
      tags: ["Cảm ứng điện từ", "Từ thông", "Faraday", "Lenz"],
    },
    {
      id: "phys_t9_nuclear_binding",
      code: "LY12.4.1",
      title: "Cấu trúc hạt nhân & Năng lượng liên kết",
      chapterId: "phys_ch4",
      chapterTitle: "Vật lí hạt nhân",
      subject: "physics",
      grade: 12,
      description: "Thành phần proton và notron, độ hụt khối Delta m = [Z*mp + (A-Z)mn] - m, năng lượng liên kết El = Delta m * c^2.",
      skills: [
        { id: "sk_p17", name: "Tính độ hụt khối và năng lượng liên kết", description: "Delta m và El = Delta m * c^2", cognitiveLevel: "remember" },
        { id: "sk_p18", name: "So sánh độ bền vững hạt nhân qua năng lượng liên kết riêng", description: "Elk / A", cognitiveLevel: "understand" },
      ],
      cognitiveLevels: ["remember", "understand", "apply"],
      supportedFormats: ["choice", "true_false_group", "numeric"],
      prerequisites: [],
      recommendedOrder: 9,
      tags: ["Hạt nhân", "Độ hụt khối", "Năng lượng liên kết riêng"],
    },
    {
      id: "phys_t10_radioactivity",
      code: "LY12.4.2",
      title: "Phóng xạ & Định luật phân rã phóng xạ",
      chapterId: "phys_ch4",
      chapterTitle: "Vật lí hạt nhân",
      subject: "physics",
      grade: 12,
      description: "Các tia phóng xạ alpha, beta+, beta-, gamma; định luật phóng xạ N(t) = N0 * 2^(-t/T) và chu kỳ bán rã T.",
      skills: [
        { id: "sk_p19", name: "Đặc điểm các tia phóng xạ", description: "Alpha, beta, gamma", cognitiveLevel: "remember" },
        { id: "sk_p20", name: "Tính lượng chất còn lại và bị phân rã", description: "N(t) = N0 * 2^(-t/T)", cognitiveLevel: "apply" },
      ],
      cognitiveLevels: ["remember", "understand", "apply"],
      supportedFormats: ["choice", "true_false_group", "numeric"],
      prerequisites: ["phys_t9_nuclear_binding"],
      recommendedOrder: 10,
      tags: ["Phóng xạ", "Chu kỳ bán rã", "Định luật phóng xạ"],
    },
  ],
};

// ============================================================================
// 3. HÓA HỌC 12 (CHEMISTRY)
// ============================================================================
export const CHEMISTRY_TAXONOMY: SubjectTaxonomy = {
  subject: "chemistry",
  nameVi: "Hóa học 12",
  icon: "FlaskConical",
  accentColor: "amber",
  examDurationMinutes: 50,
  examQuestionCount: {
    total: 28,
    part1_multipleChoice: 18,
    part2_trueFalseGroup: 4,
    part3_shortAnswer: 6,
  },
  chapters: [
    {
      id: "chem_ch1",
      number: 1,
      title: "Ester – Lipid & Xà phòng",
      subject: "chemistry",
      description: "Cấu tạo este, danh pháp, tính chất vật lý/hóa học, phản ứng este hóa, xà phòng hóa chất béo và chất giặt rửa.",
      topicIds: ["chem_t1_ester_intro", "chem_t2_lipid_fat", "chem_t3_soap_detergent"],
    },
    {
      id: "chem_ch2",
      number: 2,
      title: "Carbohydrate",
      subject: "chemistry",
      description: "Glucose, fructose, saccharose, maltose, tinh bột, cellulose: cấu trúc, tính chất hóa học và ứng dụng.",
      topicIds: ["chem_t4_monosaccharides", "chem_t5_polysaccharides"],
    },
    {
      id: "chem_ch3",
      number: 3,
      title: "Hợp chất chứa Nitrogen (Amin, Amino acid & Protein)",
      subject: "chemistry",
      description: "Amine, amino acid lưỡng tính, liên kết peptit, cấu trúc protein và phản ứng màu biuret.",
      topicIds: ["chem_t6_amines", "chem_t7_amino_acids_protein"],
    },
    {
      id: "chem_ch4",
      number: 4,
      title: "Polymer và vật liệu polymer",
      subject: "chemistry",
      description: "Phản ứng trùng hợp, trùng ngưng, chất dẻo, tơ tổng hợp, cao su và keo dán.",
      topicIds: ["chem_t8_polymer_materials"],
    },
    {
      id: "chem_ch5",
      number: 5,
      title: "Pin điện và điện phân",
      subject: "chemistry",
      description: "Thế điện cực chuẩn, pin Galvani, điện phân nóng chảy và dung dịch, hiện tượng ăn mòn kim loại.",
      topicIds: ["chem_t9_galvanic_cell", "chem_t10_electrolysis_corrosion"],
    },
    {
      id: "chem_ch6",
      number: 6,
      title: "Đại cương kim loại & Phức chất",
      subject: "chemistry",
      description: "Tính chất kim loại, dãy điện hóa, phương pháp điều chế kim loại và khái niệm phức chất cơ bản.",
      topicIds: ["chem_t11_metal_reactivity", "chem_t12_complexes"],
    },
  ],
  topics: [
    {
      id: "chem_t1_ester_intro",
      code: "HOA12.1.1",
      title: "Khái niệm Este & Phản ứng Este hóa",
      chapterId: "chem_ch1",
      chapterTitle: "Ester – Lipid & Xà phòng",
      subject: "chemistry",
      grade: 12,
      description: "Nhóm chức -COO-, este no đơn chức mạch hở CnH2nO2, đồng phân, danh pháp, mùi hương và phản ứng thủy phân axit/kiềm.",
      skills: [
        { id: "sk_c1", name: "Viết đồng phân và gọi tên este theo IUPAC", description: "Đồng phân C2H4O2, C3H6O2, C4H8O2", cognitiveLevel: "remember" },
        { id: "sk_c2", name: "Phản ứng xà phòng hóa và thủy phân este", description: "Phương trình tác dụng NaOH", cognitiveLevel: "understand" },
        { id: "sk_c3", name: "Tính khối lượng muối sau phản ứng xà phòng hóa", description: "Bảo toàn khối lượng este", cognitiveLevel: "apply" },
      ],
      cognitiveLevels: ["remember", "understand", "apply"],
      supportedFormats: ["choice", "true_false_group", "numeric"],
      prerequisites: [],
      recommendedOrder: 1,
      tags: ["Este", "Xà phòng hóa", "Đồng phân este"],
    },
    {
      id: "chem_t2_lipid_fat",
      code: "HOA12.1.2",
      title: "Lipit & Chất béo (Triglyceride)",
      chapterId: "chem_ch1",
      chapterTitle: "Ester – Lipid & Xà phòng",
      subject: "chemistry",
      grade: 12,
      description: "Triglyceride (tripanmitin, tristearin, triolein), axit béo no/không no, phản ứng hydro hóa tạo bơ nhân tạo.",
      skills: [
        { id: "sk_c4", name: "Công thức và trạng thái chất béo no, không no", description: "Triolein lỏng, Tristearin rắn", cognitiveLevel: "remember" },
        { id: "sk_c5", name: "Thủy phân chất béo sinh ra glixerol và muối axit béo", description: "Tỉ lệ phản ứng 1:3", cognitiveLevel: "understand" },
        { id: "sk_c6", name: "Bài toán cộng Br2 và đốt cháy chất béo", description: "Liên hệ nCO2 - nH2O = (k-1)n", cognitiveLevel: "apply" },
      ],
      cognitiveLevels: ["remember", "understand", "apply", "analyze"],
      supportedFormats: ["choice", "true_false_group", "numeric"],
      prerequisites: ["chem_t1_ester_intro"],
      recommendedOrder: 2,
      tags: ["Chất béo", "Triolein", "Tristearin", "Glixerol"],
    },
    {
      id: "chem_t3_soap_detergent",
      code: "HOA12.1.3",
      title: "Xà phòng & Chất giặt rửa tổng hợp",
      chapterId: "chem_ch1",
      chapterTitle: "Ester – Lipid & Xà phòng",
      subject: "chemistry",
      grade: 12,
      description: "Thành phần muối Na/K của axit béo, đầu ưa nước và đuôi kị nước, cơ chế tẩy rửa, tác hại của nước cứng.",
      skills: [
        { id: "sk_c7", name: "Cấu tạo phân tử chất giặt rửa", description: "Đầu phân cực ưa nước và đuôi kị nước", cognitiveLevel: "remember" },
        { id: "sk_c8", name: "Giải thích cơ chế giặt rửa và phản ứng trong nước cứng", description: "Tạo kết tủa muối canxi, magie", cognitiveLevel: "understand" },
      ],
      cognitiveLevels: ["remember", "understand"],
      supportedFormats: ["choice", "true_false_group"],
      prerequisites: ["chem_t2_lipid_fat"],
      recommendedOrder: 3,
      tags: ["Xà phòng", "Chất giặt rửa", "Nước cứng"],
    },
    {
      id: "chem_t4_monosaccharides",
      code: "HOA12.2.1",
      title: "Monosaccharide (Glucose & Fructose)",
      chapterId: "chem_ch2",
      chapterTitle: "Carbohydrate",
      subject: "chemistry",
      grade: 12,
      description: "Công thức phân tử C6H12O6, cấu tạo dạng mạch hở/mạch vòng, phản ứng tráng bạc với thuốc thử Tollens, lên men rượu.",
      skills: [
        { id: "sk_c9", name: "Phản ứng tráng bạc của glucose", description: "1 glucose tạo 2 Ag", cognitiveLevel: "remember" },
        { id: "sk_c10", name: "Tính lượng Ag sinh ra và khối lượng glucose tham gia phản ứng", description: "Hiệu suất phản ứng tráng bạc", cognitiveLevel: "apply" },
      ],
      cognitiveLevels: ["remember", "understand", "apply"],
      supportedFormats: ["choice", "true_false_group", "numeric"],
      prerequisites: [],
      recommendedOrder: 4,
      tags: ["Glucose", "Fructose", "Tráng bạc"],
    },
    {
      id: "chem_t5_polysaccharides",
      code: "HOA12.2.2",
      title: "Disaccharide & Polysaccharide (Saccharose, Tinh bột, Cellulose)",
      chapterId: "chem_ch2",
      chapterTitle: "Carbohydrate",
      subject: "chemistry",
      grade: 12,
      description: "Saccharose (C12H22O11), tinh bột và cellulose (C6H10O5)n: phản ứng thủy phân axit/enzim, phản ứng màu của tinh bột với iod.",
      skills: [
        { id: "sk_c11", name: "Tính chất phản ứng thủy phân saccharose và tinh bột", description: "Sản phẩm thủy phân", cognitiveLevel: "understand" },
        { id: "sk_c12", name: "Phản ứng tạo cellulose trinitrat", description: "Thuốc súng không khói", cognitiveLevel: "apply" },
      ],
      cognitiveLevels: ["remember", "understand", "apply"],
      supportedFormats: ["choice", "true_false_group", "numeric"],
      prerequisites: ["chem_t4_monosaccharides"],
      recommendedOrder: 5,
      tags: ["Saccharose", "Tinh bột", "Cellulose", "Iod"],
    },
    {
      id: "chem_t6_amines",
      code: "HOA12.3.1",
      title: "Amine (Amin)",
      chapterId: "chem_ch3",
      chapterTitle: "Hợp chất chứa Nitrogen",
      subject: "chemistry",
      grade: 12,
      description: "Khái niệm amine, bậc amine, danh pháp, tính bazo của methylamine so với anilin, phản ứng với axit HCl và nước brom.",
      skills: [
        { id: "sk_c13", name: "So sánh lực bazo của các amine", description: "CH3NH2 > NH3 > C6H5NH2", cognitiveLevel: "remember" },
        { id: "sk_c14", name: "Phản ứng tạo kết tủa trắng của anilin với dung dịch brom", description: "2,4,6-tribromoanilin", cognitiveLevel: "understand" },
      ],
      cognitiveLevels: ["remember", "understand", "apply"],
      supportedFormats: ["choice", "true_false_group", "numeric"],
      prerequisites: [],
      recommendedOrder: 6,
      tags: ["Amine", "Anilin", "Tính bazo"],
    },
    {
      id: "chem_t7_amino_acids_protein",
      code: "HOA12.3.2",
      title: "Amino acid, Peptide & Protein",
      chapterId: "chem_ch3",
      chapterTitle: "Hợp chất chứa Nitrogen",
      subject: "chemistry",
      grade: 12,
      description: "Glycine, Alanine, Lysine, Axit glutamic: tính lưỡng tính, liên kết peptit, phản ứng thủy phân và phản ứng màu biuret.",
      skills: [
        { id: "sk_c15", name: "Tính lưỡng tính của amino acid", description: "Tác dụng với cả axit và bazo", cognitiveLevel: "remember" },
        { id: "sk_c16", name: "Phản ứng màu biuret của peptide và protein", description: "Cu(OH)2 tạo phức màu tím", cognitiveLevel: "understand" },
        { id: "sk_c17", name: "Bài toán thủy phân peptide tạo muối amino acid", description: "Bảo toàn khối lượng peptide", cognitiveLevel: "apply" },
      ],
      cognitiveLevels: ["remember", "understand", "apply"],
      supportedFormats: ["choice", "true_false_group", "numeric"],
      prerequisites: ["chem_t6_amines"],
      recommendedOrder: 7,
      tags: ["Amino acid", "Peptide", "Protein", "Biuret"],
    },
    {
      id: "chem_t8_polymer_materials",
      code: "HOA12.4.1",
      title: "Polymer & Vật liệu Polymer",
      chapterId: "chem_ch4",
      chapterTitle: "Polymer và vật liệu polymer",
      subject: "chemistry",
      grade: 12,
      description: "PE, PVC, PMM, nilon-6,6, nilon-6, tơ olon; phân biệt phản ứng trùng hợp và trùng ngưng; tái chế nhựa.",
      skills: [
        { id: "sk_c18", name: "Phân loại tơ tự nhiên, nhân tạo và tổng hợp", description: "Tơ tằm, tơ visco, tơ nilon", cognitiveLevel: "remember" },
        { id: "sk_c19", name: "Phân biệt phản ứng trùng hợp và trùng ngưng", description: "Điều kiện cấu tạo monome", cognitiveLevel: "understand" },
      ],
      cognitiveLevels: ["remember", "understand"],
      supportedFormats: ["choice", "true_false_group"],
      prerequisites: [],
      recommendedOrder: 8,
      tags: ["Polime", "Trùng hợp", "Trùng ngưng", "Nilon"],
    },
    {
      id: "chem_t9_galvanic_cell",
      code: "HOA12.5.1",
      title: "Pin điện hóa & Thế điện cực chuẩn",
      chapterId: "chem_ch5",
      chapterTitle: "Pin điện và điện phân",
      subject: "chemistry",
      grade: 12,
      description: "Cặp oxi hóa - khử, thế điện cực chuẩn E°(Ox/Kh), suất điện động chuẩn của pin E°pin = E°(catot) - E°(anot).",
      skills: [
        { id: "sk_c20", name: "Xác định cực anot và catot trong pin điện", description: "Anot xảy ra quá trình oxi hóa, catot xảy ra khử", cognitiveLevel: "remember" },
        { id: "sk_c21", name: "Tính suất điện động chuẩn của pin", description: "E°pin = E°(+) - E°(-)", cognitiveLevel: "apply" },
      ],
      cognitiveLevels: ["remember", "understand", "apply"],
      supportedFormats: ["choice", "true_false_group", "numeric"],
      prerequisites: [],
      recommendedOrder: 9,
      tags: ["Pin Galvani", "Thế điện cực chuẩn", "Anot", "Catot"],
    },
    {
      id: "chem_t10_electrolysis_corrosion",
      code: "HOA12.5.2",
      title: "Điện phân & Ăn mòn kim loại",
      chapterId: "chem_ch5",
      chapterTitle: "Pin điện và điện phân",
      subject: "chemistry",
      grade: 12,
      description: "Điện phân dung dịch CuSO4, NaCl; định luật Faraday m = (A*I*t)/(n*F); ăn mòn hóa học và ăn mòn điện hóa.",
      skills: [
        { id: "sk_c22", name: "Điều kiện xảy ra ăn mòn điện hóa học", description: "Hai điện cực, tiếp xúc, dung dịch chất điện ly", cognitiveLevel: "remember" },
        { id: "sk_c23", name: "Tính khối lượng kim loại thoát ra ở catot khi điện phân", description: "m = (A*I*t)/(n*F)", cognitiveLevel: "apply" },
      ],
      cognitiveLevels: ["remember", "understand", "apply"],
      supportedFormats: ["choice", "true_false_group", "numeric"],
      prerequisites: ["chem_t9_galvanic_cell"],
      recommendedOrder: 10,
      tags: ["Điện phân", "Faraday", "Ăn mòn điện hóa"],
    },
    {
      id: "chem_t11_metal_reactivity",
      code: "HOA12.6.1",
      title: "Tính chất kim loại & Điều chế kim loại",
      chapterId: "chem_ch6",
      chapterTitle: "Đại cương kim loại & Phức chất",
      subject: "chemistry",
      grade: 12,
      description: "Dãy điện hóa kim loại, quy tắc alpha, phương pháp nhiệt luyện, thủy luyện và điện phân.",
      skills: [
        { id: "sk_c24", name: "Dự đoán chiều phản ứng theo quy tắc alpha", description: "Chất oxi hóa mạnh + chất khử mạnh -> yếu hơn", cognitiveLevel: "remember" },
        { id: "sk_c25", name: "Lựa chọn phương pháp điều chế kim loại", description: "Nhiệt luyện, thủy luyện, điện phân", cognitiveLevel: "understand" },
      ],
      cognitiveLevels: ["remember", "understand", "apply"],
      supportedFormats: ["choice", "true_false_group", "numeric"],
      prerequisites: ["chem_t9_galvanic_cell"],
      recommendedOrder: 11,
      tags: ["Kim loại", "Quy tắc alpha", "Điều chế kim loại"],
    },
    {
      id: "chem_t12_complexes",
      code: "HOA12.6.2",
      title: "Khái niệm Phức chất cơ bản",
      chapterId: "chem_ch6",
      chapterTitle: "Đại cương kim loại & Phức chất",
      subject: "chemistry",
      grade: 12,
      description: "Khái niệm nguyên tử trung tâm, phối tử, số phối trí (nội dung mới chương trình GDPT 2018).",
      skills: [
        { id: "sk_c26", name: "Nhận biết nguyên tử trung tâm và phối tử", description: "[Cu(NH3)4]2+, [Ag(NH3)2]+", cognitiveLevel: "remember" },
        { id: "sk_c27", name: "Giải thích sự hòa tan kết tủa Cu(OH)2 trong NH3 dư", description: "Tạo phức chất tan", cognitiveLevel: "understand" },
      ],
      cognitiveLevels: ["remember", "understand"],
      supportedFormats: ["choice", "true_false_group"],
      prerequisites: ["chem_t11_metal_reactivity"],
      recommendedOrder: 12,
      tags: ["Phức chất", "Nguyên tử trung tâm", "Phối tử"],
    },
  ],
};

// ============================================================================
// 4. TIN HỌC 12 (COMPUTER SCIENCE)
// ============================================================================
export const CS_TAXONOMY: SubjectTaxonomy = {
  subject: "computer_science",
  nameVi: "Tin học 12",
  icon: "Code2",
  accentColor: "indigo",
  examDurationMinutes: 50,
  examQuestionCount: {
    total: 30,
    part1_multipleChoice: 24,
    part2_trueFalseGroup: 6,
    part3_shortAnswer: 0,
  },
  chapters: [
    {
      id: "cs_ch1",
      number: 1,
      title: "Chủ đề A: Trí tuệ nhân tạo & Xã hội tri thức",
      subject: "computer_science",
      description: "Khái niệm AI, các lĩnh vực của AI (máy học, thị giác máy tính, NLP) và tác động của AI đến xã hội.",
      topicIds: ["cs_t1_ai_concepts"],
    },
    {
      id: "cs_ch2",
      number: 2,
      title: "Chủ đề B: Mạng máy tính & Giao thức mạng",
      subject: "computer_science",
      description: "Mô hình mạng, thiết bị mạng (Switch, Router), địa chỉ IPv4/IPv6, giao thức TCP/IP, DNS, HTTP.",
      topicIds: ["cs_t2_network_protocols"],
    },
    {
      id: "cs_ch3",
      number: 3,
      title: "Chủ đề C: Đạo đức & An toàn thông tin trên không gian mạng",
      subject: "computer_science",
      description: "Phòng chống mã độc, an toàn mật khẩu, bảo vệ quyền riêng tư và pháp luật trên môi trường số.",
      topicIds: ["cs_t3_security_ethics"],
    },
    {
      id: "cs_ch4",
      number: 4,
      title: "Chủ đề D: Cơ sở dữ liệu quan hệ & Truy vấn SQL",
      subject: "computer_science",
      description: "Mô hình CSDL quan hệ, bảng, bản ghi, khóa chính, khóa ngoại, câu lệnh truy vấn SQL (SELECT, WHERE, JOIN, GROUP BY).",
      topicIds: ["cs_t4_relational_database", "cs_t5_sql_queries"],
    },
    {
      id: "cs_ch5",
      number: 5,
      title: "Chủ đề F: Lập trình, Thuật toán & Đọc hiểu mã nguồn (CS Track)",
      subject: "computer_science",
      description: "Truy vết mã nguồn code trace Python/C++, vòng lặp lồng nhau, mảng/danh sách, sắp xếp, tìm kiếm và hàm đệ quy.",
      topicIds: ["cs_t6_code_trace_loops", "cs_t7_algorithms_recursion"],
    },
  ],
  topics: [
    {
      id: "cs_t1_ai_concepts",
      code: "TIN12.A.1",
      title: "Khái niệm Trí tuệ nhân tạo (AI) & Ứng dụng",
      chapterId: "cs_ch1",
      chapterTitle: "Chủ đề A: Trí tuệ nhân tạo",
      subject: "computer_science",
      grade: 12,
      description: "Khái niệm AI, AI hẹp (Narrow AI), học máy (Machine Learning), xử lý ngôn ngữ tự nhiên và thị giác máy tính.",
      skills: [
        { id: "sk_cs1", name: "Nhận biết các ứng dụng điển hình của AI", description: "Chatbot, nhận diện khuôn mặt, xe tự hành", cognitiveLevel: "remember" },
        { id: "sk_cs2", name: "Phân biệt học máy có giám sát và không giám sát", description: "Supervised vs Unsupervised Learning", cognitiveLevel: "understand" },
      ],
      cognitiveLevels: ["remember", "understand"],
      supportedFormats: ["choice", "true_false_group"],
      prerequisites: [],
      recommendedOrder: 1,
      tags: ["AI", "Trí tuệ nhân tạo", "Học máy"],
    },
    {
      id: "cs_t2_network_protocols",
      code: "TIN12.B.1",
      title: "Mạng máy tính & Giao thức Internet (TCP/IP)",
      chapterId: "cs_ch2",
      chapterTitle: "Chủ đề B: Mạng máy tính",
      subject: "computer_science",
      grade: 12,
      description: "Thiết bị mạng (Hub, Switch, Router), địa chỉ IP (IPv4, IPv6), tên miền DNS, giao thức truyền tải TCP/IP và HTTP/HTTPS.",
      skills: [
        { id: "sk_cs3", name: "Chức năng của Router, Switch và DNS", description: "Định tuyến và phân giải tên miền", cognitiveLevel: "remember" },
        { id: "sk_cs4", name: "Phân tích gói tin và cơ chế bắt tay 3 bước TCP", description: "Truyền tin cậy TCP", cognitiveLevel: "understand" },
      ],
      cognitiveLevels: ["remember", "understand", "apply"],
      supportedFormats: ["choice", "true_false_group"],
      prerequisites: [],
      recommendedOrder: 2,
      tags: ["Mạng máy tính", "TCP/IP", "Router", "DNS"],
    },
    {
      id: "cs_t3_security_ethics",
      code: "TIN12.C.1",
      title: "An toàn thông tin & Phòng chống mã độc",
      chapterId: "cs_ch3",
      chapterTitle: "Chủ đề C: An toàn thông tin",
      subject: "computer_science",
      grade: 12,
      description: "Các loại mã độc (Virus, Worm, Trojan, Ransomware), tấn công giả mạo (Phishing), mã hóa đối xứng/bất đối xứng.",
      skills: [
        { id: "sk_cs5", name: "Nhận diện dấu hiệu tấn công lừa đảo (Phishing)", description: "Email/liên kết giả mạo", cognitiveLevel: "remember" },
        { id: "sk_cs6", name: "Nguyên lý mã hóa khóa công khai và chữ ký số", description: "Bảo mật và toàn vẹn dữ liệu", cognitiveLevel: "understand" },
      ],
      cognitiveLevels: ["remember", "understand"],
      supportedFormats: ["choice", "true_false_group"],
      prerequisites: [],
      recommendedOrder: 3,
      tags: ["An toàn thông tin", "Phishing", "Mã độc", "Chữ ký số"],
    },
    {
      id: "cs_t4_relational_database",
      code: "TIN12.D.1",
      title: "Mô hình Cơ sở dữ liệu quan hệ (RDBMS)",
      chapterId: "cs_ch4",
      chapterTitle: "Chủ đề D: Cơ sở dữ liệu quan hệ",
      subject: "computer_science",
      grade: 12,
      description: "Bảng, trường, bản ghi, khóa chính (Primary Key), khóa ngoại (Foreign Key), quan hệ 1-1, 1-N, N-N.",
      skills: [
        { id: "sk_cs7", name: "Xác định khóa chính và khóa ngoại trong bảng CSDL", description: "Ràng buộc toàn vẹn thực thể và tham chiếu", cognitiveLevel: "remember" },
        { id: "sk_cs8", name: "Phân tích cấu trúc liên kết giữa các bảng", description: "Quan hệ 1-N", cognitiveLevel: "understand" },
      ],
      cognitiveLevels: ["remember", "understand", "apply"],
      supportedFormats: ["choice", "true_false_group"],
      prerequisites: [],
      recommendedOrder: 4,
      tags: ["CSDL", "Khóa chính", "Khóa ngoại", "Quan hệ"],
    },
    {
      id: "cs_t5_sql_queries",
      code: "TIN12.D.2",
      title: "Ngôn ngữ truy vấn SQL (SELECT, WHERE, JOIN)",
      chapterId: "cs_ch4",
      chapterTitle: "Chủ đề D: Cơ sở dữ liệu quan hệ",
      subject: "computer_science",
      grade: 12,
      description: "Truy vấn dữ liệu với cú pháp SQL: SELECT, FROM, WHERE, ORDER BY, GROUP BY, HAVING, INNER JOIN.",
      skills: [
        { id: "sk_cs9", name: "Đọc hiểu câu lệnh SQL cơ bản", description: "SELECT các cột thỏa mãn điều kiện WHERE", cognitiveLevel: "understand" },
        { id: "sk_cs10", name: "Xác định kết quả trả về của truy vấn SQL có JOIN và GROUP BY", description: "Truy vấn kết nối bảng", cognitiveLevel: "apply" },
      ],
      cognitiveLevels: ["understand", "apply", "analyze"],
      supportedFormats: ["choice", "true_false_group"],
      prerequisites: ["cs_t4_relational_database"],
      recommendedOrder: 5,
      tags: ["SQL", "SELECT", "JOIN", "Truy vấn CSDL"],
    },
    {
      id: "cs_t6_code_trace_loops",
      code: "TIN12.F.1",
      title: "Truy vết mã nguồn vòng lặp (Code Trace)",
      chapterId: "cs_ch5",
      chapterTitle: "Chủ đề F: Lập trình & Thuật toán",
      subject: "computer_science",
      grade: 12,
      description: "Đọc hiểu và dự đoán giá trị biến trong các đoạn mã Python và C++ có vòng lặp for, while, vòng lặp lồng nhau.",
      skills: [
        { id: "sk_cs11", name: "Truy vết từng bước giá trị biến qua vòng lặp for/while", description: "Bảng trace table", cognitiveLevel: "understand" },
        { id: "sk_cs12", name: "Dự đoán đầu ra của 2 vòng lặp lồng nhau", description: "Ma trận hoặc tam giác lặp", cognitiveLevel: "apply" },
      ],
      cognitiveLevels: ["understand", "apply", "analyze"],
      supportedFormats: ["choice", "code_trace", "true_false_group"],
      prerequisites: [],
      recommendedOrder: 6,
      tags: ["Code Trace", "Vòng lặp", "Python", "C++"],
    },
    {
      id: "cs_t7_algorithms_recursion",
      code: "TIN12.F.2",
      title: "Thuật toán sắp xếp, tìm kiếm & Hàm đệ quy",
      chapterId: "cs_ch5",
      chapterTitle: "Chủ đề F: Lập trình & Thuật toán",
      subject: "computer_science",
      grade: 12,
      description: "Tìm kiếm nhị phân, sắp xếp nổi bọt / chèn / chọn, hàm đệ quy (tính giai thừa, Fibonacci, tính tổng).",
      skills: [
        { id: "sk_cs13", name: "Nhận biết điều kiện cơ sở của hàm đệ quy", description: "Tránh đệ quy vô hạn", cognitiveLevel: "understand" },
        { id: "sk_cs14", name: "Dự đoán giá trị trả về của hàm đệ quy", description: "Đệ quy cây hoặc đệ quy đuôi", cognitiveLevel: "apply" },
      ],
      cognitiveLevels: ["understand", "apply", "analyze"],
      supportedFormats: ["choice", "code_trace", "true_false_group"],
      prerequisites: ["cs_t6_code_trace_loops"],
      recommendedOrder: 7,
      tags: ["Đệ quy", "Tìm kiếm nhị phân", "Sắp xếp"],
    },
  ],
};

export const ALL_GRADE_12_TAXONOMIES: Record<Grade12Subject, SubjectTaxonomy> = {
  math: MATH_TAXONOMY,
  physics: PHYSICS_TAXONOMY,
  chemistry: CHEMISTRY_TAXONOMY,
  computer_science: CS_TAXONOMY,
};

export function getTaxonomyBySubject(subject: Grade12Subject): SubjectTaxonomy {
  return ALL_GRADE_12_TAXONOMIES[subject];
}

export function getAllGrade12Topics(): TaxonomyTopic[] {
  return [
    ...MATH_TAXONOMY.topics,
    ...PHYSICS_TAXONOMY.topics,
    ...CHEMISTRY_TAXONOMY.topics,
    ...CS_TAXONOMY.topics,
  ];
}

export function findTopicById(topicId: string): TaxonomyTopic | undefined {
  return getAllGrade12Topics().find((t) => t.id === topicId);
}
